### ISSUE TITLE
check code coverage, and add any low-hanging tests

### ISSUE THREAD

**Issue by increpare** [increpare/PuzzleScript#1001]
seems i have about 90% coverage of the core files 

compiler.js 9.1% (10kb/117kb)
parser.js 12.1% (10kb/83kb)
engine.js 13.5% (11kb/88kb)

**Comment by increpare** [comment]
Audit notes:

Generally surprised by how many untested cases I found while doing coverage tested. Happy I fixed one not insignifcant performance bug also!  Here are more detailed notes I took as I was going.

PARSER.JS

added tests:
* "cannot assign sound events to aggregate objects"
* coverage for "if (splits[i].toLowerCase() !== 'or')" branch in legend

Other unreachable code

* Some logging code, but idgaf. 
*Internet explorer shims lol.
* TooManyErrors calls...we have an issue for that (I thought at least)
* copystate stuff is used by codemirror
* 'no such section as X" probably unreachable
* removed unnecessary breaks after return in swich statement
* removed unreachable 'Invalid character "' + ch + '" message
* probably unreachable "no layers found." error
* maybe unreachable "Detected a comment where I was expecting a level."

COMPILER.JS

I added some tests to trigger certain errors/cover certain functions
* colour palette selection errors
* "You need to have some objects defined" error
* to cover the function rightBracketToRightOf
* "Error, an item can only have one direction/action at a time" error
* "title Error, you can only use \"->\" once in a rule"
* "Object names should only be used within cells"
* "this rule refers to nothing*
* cover getPropertiesFromCell
* cover concretizeMovingInCellByAmbiguousMovementName
* "You cannot use 'no' to exclude the aggregate object"
* "Error in win condition:" for second slot
* remove uncalled validseed function
* removed duplicate state.invalid check
* There's some code for unit_testing that's unintentional unreachable (dealing with verbose_logging/debug mode/ DOM-manipulation)

Other unreachable code
* 'Invalid color specified for object" doesn't seem to be reachable. I think the parser catches invalid colour format for objects before then.  
* "'Object not found with name ' + n" doesn't seem to be reachable.
* "you have to define something to be the background" is not reachable because it is pre-empted by the error message "you have to define something to be the background", and in that code if a background isn't found it's just set to a default value. So I just removed the error.
* logWarning('Message too long to fit on screen.', level[2]); incorrect marked by chrome as notreached - if I run the test by itself it's reached.
* 'Spooky error!  Empty line passed to rule function.' seems unreachable, just there as a precaution.
(Seemingly-)unreachable errors are probably safer to leave in than to remove.
* 'Cannot end a rule with ellipses.' seems to be pre-empted by "There's no point in putting an ellipsis at the very start or the end of a rule" whenever I tried to trigger it.  This code is so hairy though I won't risk taking it out.
* "You have an totally empty pattern on the left-hand side.  This will match *everything*.  You certainly don't want this." seems to not be reachable, is pre-empted by other messages. And frankly I don't even agree with what it's saying...
* some directionaggregates unfolding code that's never reached (~line 901 in compiler.js).  It's in such a delicate area I dare not remove it ( https://github.com/increpare/PuzzleScript/commit/a4759583d297f57561021fd78756e586971a7880 )
* Found some weird seemingly-unreachable code in #1004 to do with synonym processing (the code for building up synonym/property/aggregate dictionaries is generally a bit messy)
* "Oops!  " + object_name.toUpperCase() + " not assigned to a layer." is essentially covered by  "Object "X" has been defined, but not assigned to a layer."  I tried to trigger it but no idea how to. Leaving it in because it's somewhere delicate.
* `Wasn't able to make sense of "${s}" as a dimension.` I don't think I can hit this - the earlier int checks shouldn't allow anything to pass, but there's no harm in leaving it.
* "if (wincondition.length == 0)" check that should never be triggered (a null wincondition is just a null wincondition)
* a length check in generateSoundData that should never be triggered, but leaving it just to be save
* "Expecting sfx data, instead found \"" + seed + "\"." is getting pre-empted by "Was expecting a soundverb here (MOVE, DESTROY, CANTMOVE, or the like), but found something else"
* "too much stuff to define a sound event." seems to be unreachable
* lots of sound declaration stuff in the compiler is seemingly unreachable, being dealt with already by the parser


ENGINE.JS

The vast majority of uncovered code in engine.js is debug statements for verbose_logging. These are disabled during unit testing.

(other examples of code unaccessed during unit testing - 
* title screen display code
* level editor code
* code dealing with winning levels
* checkpoint code
* graphics code

That's accounts for basically all of the remaining uncovered code in engine.js

I did however come across bug #1003, the fixing of which sped up the engine quite a bit! (17s->16s unit testing time)


---

The states...went
compiler 9k/118k 8% (from 9.1%)
parser 9k/83k 11.2% (from 12.1%)
engine 12k/88k 13.6% (from 13.5%????)

Not sure what's happening with engine.js...I guess the numbers are a bit fuzzy...maybe it's counting comments weirdly.

**Comment by david-pfx** [comment]
Wow. I am impressed. But yes, when you add tests and go looking you always find stuff you didn't know about and need to fix.
Once you've got this settled down and moved onto other things, I'll try a merge with PS Next and see how it goes. I'm willing to bet I find stuff I didn't know about and need to fix.😁
