### ISSUE TITLE
"Too many errors/warnings; aborting compilation" incorrectly displayed when in-game (should be worded differently)

### ISSUE THREAD

**Issue by increpare** [increpare/PuzzleScript#1002]
e.g. https://www.puzzlescript.net/editor.html?hack=fc70cac2beeb773dbe6c9859fd38d986 and try to move

**Comment by david-pfx** [comment]
That's not the error I'm seeing.

**Comment by increpare** [comment]
@david-pfx that's because the issue is fixed?

(to be sure, the message now should be: 'Too many errors/warnings; noping out.'  )
