### ISSUE TITLE
"Too many errors/warnings; noping out" after 100 moves with errors

### ISSUE THREAD

**Issue by pancelor** [increpare/PuzzleScript#1012]
I was playing [tiny treasure hunt 1.0](https://www.puzzlescript.net/editor.html?hack=6893137) today and it kept mysteriously freezing. I opened the hack link and checked the console:

```
=================================
Successful Compilation, generated 52 instructions.
line 242 : Got caught looping lots in a rule group :O
line 242 : Got caught looping lots in a rule group :O
line 242 : Got caught looping lots in a rule group :O
...
line 242 : Got caught looping lots in a rule group :O
line 242 : Got caught looping lots in a rule group :O
line 242 : Got caught looping lots in a rule group :O     //this was the 101st copy of this error
Too many errors/warnings; noping out.
line 242 : Got caught looping lots in a rule group :O
Too many errors/warnings; noping out.
line 242 : Got caught looping lots in a rule group :O
Too many errors/warnings; noping out.
```

Maybe the "Too many errors" check should reset its error count at the start of each player turn, so that games that error once every turn will continue to run?

**Comment by david-pfx** [comment]
The error count is for compile errors -- runtime errors should not be counted at all.

But this program is buggy. The dev must have seen the error -- it should have been fixed.

**Comment by increpare** [comment]
>The error count is for compile errors -- runtime errors should not be counted at all.
Runtime errors of the sort in this game - non-terminating loops, should definitely be counted.  

It's likely the error messages weren't there when the game was originally programmed. And as an anonymous gist, it can't be modified.

I'll look into this more carefully and see if I can.

The second level from the game seems to more consistently reproduce the error - here's a unit test


[
"tiny treasure hunt 1.0",
["title tiny treasure hunt 1.0\nauthor Weeble\nhomepage www.twitter.com/weeble\nrun_rules_on_level_start\n\n========\nOBJECTS\n========\nLowFloorRaw\nBLACK\n\nLowFloor1\n#111411 #191d19 #202020 #252725\n01011\n12310\n23320\n02321\n02110\n\nLowFloor2\n#111411 #191d19 #202020 #252725\n01001\n22312\n12331\n01310\n10101\n\nWallFacade\n#555555 #666666 #777777\n21221\n10011\n.....\n.....\n.....\n\nHighFloor\n#909090 #999999 #bbbbbb #cccccc\n33232\n31012\n20002\n31012\n32222\n\nLowPlayer\n#686868 #707070 #787878 #808080\n.....\n.....\n.232.\n.121.\n.0.0.\n\nHighPlayer\n#e8e8e8 #f0f0f0 #f8f8f8 #ffffff\n.232.\n.121.\n.0.0.\n.....\n.....\n\nCrate\n#999944 #88883a #777733\n10001\n00000\n10001\n22222\n22222\n\nHighCrate\n#dddd55 #eeee50 #cccc48\n10001\n00000\n10001\n22222\n22222\n\nBurntCrate\n#222222 #111111 #000000\n10001\n00000\n10001\n22222\n22222\n\nMeltingIce\nWhite LightBlue #9999ff #330000\n.33..\n3333.\n31013\n11330\n21112\n\n\nStaticIce\nWhite LightBlue #9999ff\n10002\n1...0\n0...1\n10012\n21122\n\nIceCubeN\nWhite LightBlue #9999ff\n10002\n1...0\n0...1\n10012\n21122\n\nIceCubeE\nWhite LightBlue #9999ff\n10002\n1...0\n0...1\n10012\n21122\n\nIceCubeS\nWhite LightBlue #9999ff\n10002\n1...0\n0...1\n10012\n21122\n\nIceCubeW\nWhite LightBlue #9999ff\n10002\n1...0\n0...1\n10012\n21122\n\nFirePit1\n#990000 #770000 #550000 #330000\n02111\n13321\n02321\n32110\n23121\n\nFirePit2\n#990000 #770000 #550000 #330000\n10311\n21233\n11021\n23213\n20122\n\n\nPillar\n#cccccc #dddddd #eeeeee #ffffff #bbbbbb #aaaaaa\n32123\n33333\n02120\n22122\n01310\n\nIceCubeShadow\nRED\n.....\n.....\n..0..\n.....\n.....\n\nCoin\nWHITE #eeee55 #aaaa33\n.000.\n01112\n01212\n01112\n.222.\n\n \nStairsNorth\n#333333 #444444 #555555 #666666 #777777\n44444\n43334\n32223\n21112\n10001\n=======\nLEGEND\n=======\n. = LowFloorRaw\n\" = HighFloor\n@ = LowPlayer and LowFloorRaw\n$ = Coin and HighFloor\n£ = Coin\nH = HighCrate and HighFloor\n: = WallFacade and FirePit1 and LowFloorRaw\n~ = WallFacade and LowFloorRaw\n# = Crate and LowFloorRaw\nW = Crate and LowFloorRaw and WallFacade\n! = FirePit1 and LowFloorRaw\nI = Pillar and HighFloor\n% = StaticIce and LowFloorRaw\n& = StaticIce and LowFloorRaw and WallFacade\n/ = StairsNorth and LowFloorRaw\nFirePit = FirePit1 or FirePit2\nLowFloor = LowFloor1 or LowFloor2\nBackground = LowFloor or HighFloor or LowFloorRaw\nPlayer = LowPlayer or HighPlayer\nObstacle = StairsNorth\nBlocksLow = Crate or HighFloor or StaticIce or Pillar or BurntCrate\nPushable = Crate or StaticIce\nMovingIce = IceCubeE or IceCubeS or IceCubeW or IceCubeN\nIceCube = StaticIce or MovingIce\nGrounded = IceCube or LowPlayer or Crate\n\n=======\nSOUNDS\n=======\n\nCoin DESTROY 77169700\nCrate MOVE 24442507\nSFX0 98605308 ( Hiss )\nSFX1 89033504 ( Snap )\nSFX2 70543502 ( Plink )\nSFX3 34905302 ( Slam )\nSFX4 93355705 ( Squeak )\nSFX5 52776702 ( Grind )\nSFX6 86238705 ( Bounce )\n\n================\nCOLLISIONLAYERS\n================\n\nBackground\nStairsNorth, FirePit\nWallFacade\nCrate, IceCube, MovingIce, LowPlayer, MeltingIce, BurntCrate\nPillar, HighPlayer, HighCrate, Coin\nIceCubeShadow\n\n======\nRULES \n====== \n\n(Make stuff pretty)\n[ LowFloorRaw ] -> [ random LowFloor ]\n[ FirePit ] -> [ random FirePit ]\n\n(Pushing stuff)\n[ > LowPlayer | Pushable ] -> [ > LowPlayer | > Pushable ]\n[ > HighPlayer | HighCrate ] -> [ > HighPlayer | > HighCrate ]\n\n(Don't walk under pillars. Probably redundant.)\n[ > Grounded | Pillar ] -> [ Grounded | Pillar ]\n\n(Ice melts in lava)\n[ MeltingIce FirePit ] -> [ ]\n[ IceCube FirePit ] -> [ MeltingIce FirePit ] sfx0 again\n\n(Ice slides)\nRIGHT [ > StaticIce ] -> [ > IceCubeE ] sfx2\nDOWN [ > StaticIce ] -> [ > IceCubeS ] sfx2\nLEFT [ > StaticIce ] -> [ > IceCubeW ] sfx2\nUP [ > StaticIce ] -> [ > IceCubeN ] sfx2\n[ MovingIce no IceCubeShadow ] -> [ MovingIce IceCubeShadow ]\nRIGHT [ IceCubeE ] -> [ > IceCubeE ] again\nDOWN [ IceCubeS ] -> [ > IceCubeS ] again\nLEFT [ IceCubeW ] -> [ > IceCubeW ] again\nUP [ IceCubeN ] -> [ > IceCubeN ] again\n\n(Stop things from overlapping the stairs)\n[ > IceCube | Obstacle ] -> [ StaticIce | Obstacle ]\n[ > Crate | Obstacle ] -> [ Crate | Obstacle ]\n\n(Lava kills you)\nlate [ LowPlayer FirePit ] -> [ FirePit ] sfx5 message Ouch, hot!\n\n(More ice rules)\nlate [ MovingIce IceCubeShadow ] -> [ StaticIce ] sfx5\nlate [ IceCubeShadow ] -> [ ]\n\n(Crates get charred in lava)\nlate [ Crate FirePit ] -> [ BurntCrate FirePit ] sfx5\n\n(Player collects coins)\n[ > HighPlayer | Coin HighFloor ] -> [ | HighPlayer HighFloor ]\n[ > LowPlayer | Coin LowFloor ] -> [ | LowPlayer LowFloor ]\n\n(Player can climb stairs)\nUP [ > LowPlayer StairsNorth | HighFloor ] -> [ StairsNorth | HighPlayer HighFloor ] sfx6\n\n(Stop things from getting pushed up onto ledges)\n[ > Grounded | HighFloor ] -> [ Grounded | HighFloor ]\n\n(Players and crates fall)\nlate [ HighPlayer no BlocksLow ] -> [ LowPlayer ] sfx1 again\nlate [ HighCrate no BlocksLow ] -> [ Crate ] sfx1 again\n\n==============\nWINCONDITIONS\n==============\n\nNo Coin\n\n======= \nLEVELS\n=======\n\n..........£\n.!!!!!!!!!.\n.!!!!!!!!!.\n.!!.%%%.!!.\n.!!%...%!!.\n.!!%.@.%!!.\n.!!%...%!!.\n.!!.%%%.!!.\n.!!!!!!!!!.\n.!!!!!!!!!.\n...........\n\n\n",[0,0,3,2,3,1,2,3,1,2,2,0,1,1,2,3,0,1,1,3,0,1,3,0,1,0,3,2,2,3,3,3,2,1,1,1,0,0,0,0,1,2,3,0,1,2,3,0,1,2],"lowfloor2:0,0,0,0,lowfloor1:1,1,0,1,1,0,1,\n0,firepit1 lowfloor1:2,2,firepit1 lowfloor2:3,firepit2 lowfloor1:4,4,3,2,4,4,0,\n1,2,2,4,1,1,0,2,3,2,1,\n0,4,3,1,1,0,0,0,3,2,0,\n1,4,2,0,1,0,1,0,1,3,0,\n0,4,1,0,1,0,lowfloor1 lowplayer:5,0,4,2,0,\n1,firepit2 lowfloor2:6,2,1,0,0,0,0,0,4,1,\n0,2,3,0,1,1,1,1,1,4,1,\n1,6,4,0,1,1,6,1,2,3,0,\n0,6,3,1,4,6,3,3,4,6,1,\ncoin lowfloor2:7,1,0,0,0,0,1,1,1,1,1,\n",0,"1714648660236.5208",[]]
],

**Comment by increpare** [comment]
This was fixed in the 1.1 version of the game. So at least I should update the gallery link..
https://www.puzzlescript.net/editor.html?hack=d9edc0b4d587f688b3495c834ca4735297d40e52

**Comment by increpare** [comment]
So, looking into this, the offending changelist is this one
https://github.com/increpare/PuzzleScript/commit/da0fd9e3f1ee02fc8b163dc3dede33242ac2340c

which was included to stop games freezing up the puzzlescript editor (#855) . I think this is good-behaviour, really. 

Supporting existing games is a really high priority of mine with puzzlescript, but given that this game was already 'fixed' (though I hadn't linked to the updated version in the gallery), and the stability considerations, I think I'm okay to let this one go?

**Comment by david-pfx** [comment]
That link is 404.
