### ISSUE TITLE
windows/chrome gaps between tiles wtf

### ISSUE THREAD

**Issue by increpare** [increpare/PuzzleScript#1015]
e.g. this game https://www.puzzlescript.net/play.html?p=838c19cf7834883569b20d7d6a74359b

![image](https://github.com/increpare/PuzzleScript/assets/465632/e2267021-205c-4cda-9edd-6ccba53d00c1)

and in firefox (Wtf)

![image](https://github.com/increpare/PuzzleScript/assets/465632/b79bab8d-fc87-4be7-9753-3e270bff102b)

**Comment by increpare** [comment]
oh the game has 5x4 tiles lol

**Comment by david-pfx** [comment]
Shouldn't the compiler warn then? In PS Next this does not happen.
