### ISSUE TITLE
properties bug(?) no flow flow_up on rhs allowed

### ISSUE THREAD

**Issue by increpare** [increpare/PuzzleScript#1017]
v. complex example, needs to be simplified
https://www.puzzlescript.net/editor.html?hack=43cebc58529f81ed86279ca7b3117820

**Comment by david-pfx** [comment]
Needs more info.
* What's the problem?
* What steps to reproduce?
* What do you see?
* What would you expect to see?

**Comment by increpare** [comment]
[here](https://www.puzzlescript.net/editor.html?hack=b0aac2f5057de732fb0c4c5dab4434b0)'s a simpler example:

```
a_or_b = a or b

[ c ] -> [ a no a_or_b ]
[ d ] -> [ no a_or_b b ]
```

what's the problem? somewhat unclear semantics - it's somewhat paradoxical-seeming typing "no a_or_b a" on the right-hand side of a rule.  on the other hand, the only sensible way to interpret it is "remove the property, and add the non-property"

simplifying it further, even this is allowed:

```
[ c ] -> [ a no a ]
```

this is a catastrophically simplified variant of the first instruction, that could trigger a warning (the way that it does if it's on the left-hand side 

```
[ a no a ] -> [  ]
```
).

But, I think this is fine overall.  It's something of a spooky corner of rule-semantics, with some degenerate forms, but it seems that it always has either one meaningful interpretation, or else is nonsense.
