### ISSUE TITLE
"no restart" makes no sense

### ISSUE THREAD

**Issue by ZackZparrow** [increpare/PuzzleScript#1022]
If you enable "norestart", players can still quit to menu and continue which restart the level. Therefore "norestart" is meaningless right now

**Comment by david-pfx** [comment]
This is a feature inherited from PS+, and needs to retain compatibility. It does the job of suppressing any kind of restart in-game, but it has no effect on the 'continue' option that appears on the start menu, which you can always get to by exiting the game and running it again. I think PS+ does the same. 

It's not obvious how this could be resolved. What would you like it to do?

**Comment by ZackZparrow** [comment]
Two options are possible: Either add "nocontinue" or make "norestart" remove both restart and continue. I think the first option is redundant and the second option is better for keeping puzzlescript simple. At the end of the day, if i use "norestart" that means i want failed players to start over from the beginning.

**Comment by ZackZparrow** [comment]
But second option also prevents people to continue genuinely. Because not all people use continue for "cheating"

Actually unlike restart, continue should save each movement and continue from the latest movement. That would solve everything. But that's a hard thing to do in puzzlescript i suppose.

At this point the best you can do is adding "nocontinue" which removes the continue option in main menu

**Comment by ZackZparrow** [comment]
Oh gosh. How did i not think of this,  the solution is extremely simple:

[ Player ] -> checkpoint

That saves each turn and continue from the latest turn. Gonna close this issue since it's solved

**Comment by david-pfx** [comment]
Yes, checkpoint is the one way to restart at a point within a level. It also blocks the use of UNDO to effect a restart. I'm happy to leave it at that.
