### ISSUE TITLE
Online editor error

### ISSUE THREAD

**Issue by MatttNguyen** [increpare/PuzzleScript#1025]
When I open https://www.puzzlescript.net/editor.html I was welcomed by a blank white screen and the text "0"
<img width="1792" alt="image" src="https://github.com/user-attachments/assets/ff0995d8-4fce-4acc-a671-9bc44c0809b0">

**Comment by MatttNguyen** [comment]
Btw 69th issue les goooo

**Comment by increpare** [comment]
@MatttNguyen Hi, thanks for the report.  Could you let me know what browser/operating system you're using?  Could you force-refresh (shift+f5 maybe) and let me know if it's still a problem.

**Comment by MatttNguyen** [comment]
everything else works fine except for that link

**Comment by MatttNguyen** [comment]
and yes, i can hack, so i just access the editor from there?

**Comment by MatttNguyen** [comment]
> @MatttNguyen Hi, thanks for the report. Could you let me know what browser/operating system you're using (and what version of the browser)? Could you force-refresh (shift+f5 maybe) and let me know if it's still a problem. I can't reproduce it here on windows/edge....
> 
> If the problem has persisted, could you also view-source and let me know if the page is just an 0, or if it secretly contains something else in addition perhaps? And, if you could [open the javascript-console](https://support.travelpayouts.com/hc/en-us/articles/360003418472-How-to-open-the-JavaScript-console#:~:text=The%20console%20opens%20up%20as,Opt%2BJ%20(for%20Mac)) and let me know if there are any errors there, that might be elucidating.

the source is normal, and the console is empty

**Comment by MatttNguyen** [comment]
its funny that puzzlescript plus also has the same exact issue except it's a 9 instead of a 0

**Comment by MatttNguyen** [comment]
> > @MatttNguyen Hi, thanks for the report. Could you let me know what browser/operating system you're using (and what version of the browser)? Could you force-refresh (shift+f5 maybe) and let me know if it's still a problem. I can't reproduce it here on windows/edge....
> > If the problem has persisted, could you also view-source and let me know if the page is just an 0, or if it secretly contains something else in addition perhaps? And, if you could [open the javascript-console](https://support.travelpayouts.com/hc/en-us/articles/360003418472-How-to-open-the-JavaScript-console#:~:text=The%20console%20opens%20up%20as,Opt%2BJ%20(for%20Mac)) and let me know if there are any errors there, that might be elucidating.
> 
> the source is normal, and the console is empty

oh and im using mac so :(

**Comment by increpare** [comment]
>and yes, i can hack, so i just access the editor from there?
It _should_ just work regardless of the particular url lol.

> oh and im using mac so :(
@MatttNguyen What browser are you using? Safari? Could you tell me what version (Safari->About Safari should show the version number in a window). Do you have any browser extensions installed?

**Comment by MatttNguyen** [comment]
nah im using chrome and im not using any extensions (at least that's affecting the website)

**Comment by MatttNguyen** [comment]
and https://www.puzzlescript.net/editor.html?hack=0 works for some reason

**Comment by increpare** [comment]
I can't reproduce it - it's all very weird.  If it's still an issue for anyone I can look into it again, but...as is, I have no idea - one other option would be to see if there's anything in the local storage (in german: "lokaler Speicher").  I'd be specifically interested, if there's anything in saves, if you could paste the data in a comment.  If you supply that I can re-open the comment and look again.

<img width="1472" alt="Bildschirmfoto 2024-12-03 um 15 15 08" src="https://github.com/user-attachments/assets/99743a32-1ce7-49d8-8038-b52bcf5a9299">
