### ISSUE TITLE
Bug when undoing a restart into an again loop

### ISSUE THREAD

**Issue by beekie18** [increpare/PuzzleScript#1026]
Hello,

I ran into a bug in a scenario like this:

1. the engine is hitting an 'again' loop through the rules
2. the user hits the restart key
3. the user hits the undo key

Here's a minimal reproducible example: https://www.puzzlescript.net/editor.html?hack=d0132c7f27dc5c3e8d0bc97d05fea328
The goal is to get to the flag. Pressing right puts the crate onto the conveyor belts, which puts the game in an infinite 'again' loop. This should make this level impossible. However, restarting and then undoing the restart allows the user to press right again, interrupting the conveyor belts.

As far as I can tell, what should happen is what happens with a normal undo while in an again loop: the game goes back to the state before the 'again' was started. In the example above, the player character should end up on the tile it was on before the crate ended up on the arrows. 

I  was working on a game when I found this bug, and the bug is completely game-breaking. I want an infinite loop to be a failure state the user can undo out of, but with this bug, they can bypass it. 

Let me know if you need any more information from me.

Thanks!

Edit: minimized the code even more.
Edit: I thought for a bit it was maybe the late-ness of the again rules that are the problem, but you can cause a similar issue even if the two late rules are made not late: https://www.puzzlescript.net/editor.html?hack=c8145ab64c0a75ea2a46b8c1ec347352 (you'll need to press right and then down to cause the infinite loop, and then restart and undo the restart to cause the bug, and then you can get out of the infinite loop when you shouldn't be able to)

**Comment by beekie18** [comment]
Ack, my minimum reproducible example doesn't actually reproduce the bug! Let me try to make one that does...

**Comment by david-pfx** [comment]
Looks to me like this might be a problem in `restart` going back to the wrong place when `again` is happening.

**Comment by increpare** [comment]
Fixed now - will upload later.  Interestingly/mildly annoyingly, there's no way to write a test for this as is, as the tests always assume that 'agains' run to completion.  I don't think it's worth changing my test framework just for this bug - let's hope it doesn't bite me in the ass in future ^^

**Comment by beekie18** [comment]
Amazing, thank you! How will I know when the fix is live?

**Comment by increpare** [comment]
@beekie18 when the terminal says a date newer than "build 1767, 2-may-2024" when you launch it it'll have been fixed :)

**Comment by increpare** [comment]
@beekie18 (live now)
