### ISSUE TITLE
Restart plus message does not work as expected

### ISSUE THREAD

**Issue by david-pfx** [increpare/PuzzleScript#1039]
1) Load Basic Example in PS (David Skinner's game).
2) Simply add this line in rules: late [Crate | Crate ] -> restart message fail

Expected behaviour: When pushing two crates next to each other, display message and restart level.

What actually happens: It displays the message and moves to next level, i.e., it ignores the restart.

Note1: The issue is the same with the keyword `cancel`
Note2: The issue seems to rise when combining restart/cancel with message.

(@ Orcenhaze on Discord)

**Comment by increpare** [comment]
duplicates  #1038
