### ISSUE TITLE
Pressing E on 'insert cartridge' screen doesn't open editor

### ISSUE THREAD

**Issue by Draknek** [increpare/PuzzleScript#150]
(This isn't a new bug, it's been the case for ages)

**Comment by increpare** [comment]
What's the desired behaviour? new 5x5 'blank' map?

**Comment by Draknek** [comment]
Same behaviour as pressing E on the title screen, or clicking "level editor" on the "insert cartridge" or any other screen! (Load the first level)

**Comment by increpare** [comment]
ok. If you press e while not in a level, load the level. if there isn't a level, then create a blank 5x5 one and edit that.
