### ISSUE TITLE
helpful changes for automation

### ISSUE THREAD

**Issue by increpare** [increpare/PuzzleScript#172]
"event listeners and set interval should not be added during unitTesting, and also it would be convenient to keep the flag that prevents unit tests from automatically advancing levels."

cf https://github.com/increpare/PuzzleScript/pull/162#issuecomment-41217242

**Comment by increpare** [comment]
I don't want to take responsibility for automation support.

**Comment by increpare** [comment]
(but the stuff you did was cool!)

**Comment by JoeOsborn** [comment]
For sure, no worries!
