### ISSUE TITLE
verbose_logging: single-cell rules don't need direction shown

### ISSUE THREAD

**Issue by Draknek** [increpare/PuzzleScript#182]
When verbose_logging is on, the output includes the rule number and the direction of matching, e.g. "Rule 284 down applied"

However, if a rule just matches against a single cell, this information is a bit confusing. It would be clearer imo if the debug output was "Rule 284 applied".

**Comment by increpare** [comment]
will only output direction info now for rules where there are directional variants.

so 

right [cat|dog]->[dog|dog] 

wouldn't need a directional indicator either.
