### ISSUE TITLE
better multiline messages

### ISSUE THREAD

**Issue by rmmh** [increpare/PuzzleScript#197]
currently, if someone wants to do a multi-line message, they have to manually pad lines to the appropriate length so they display properly. A better way to indicate new lines (\n? "message_nextline" directive?) would make it less annoying

`message The Princess is in need!                                 ''''''''''''''''''''''''''''''''''>Listen to the princess by pressing x next to her.`

**Comment by increpare** [comment]
closing. can't think of a nice way to solve this, and also don't want to add anything that would encourage people to use more text.
