### ISSUE TITLE
try higher-resolution font

### ISSUE THREAD

**Issue by increpare** [increpare/PuzzleScript#199]
The legibility of the current one is so awful.

**Comment by sfiera** [comment]
Any design constraints? Square? Monospace?

A brief look at the code suggests that a rectangular font wouldn't require much extra code. Rectangular is probably more readable than square, and 5-by-5 squares could stay central to the design (with the addition of ascenders and descenders).

**Comment by increpare** [comment]
I don't know. This bug is me griping about a problem. But in some ways, it's okay if it's terrible - puzzlescript isn't really for text-based games and most games with lots of text ... I don't feel that changing the engine to cater to them is necessarily a good idea ... 

So I don't know.  If you want to have a play around and see, great, but I don't know what I'll accept...

**Comment by sfiera** [comment]
Sure, I won't get my hopes up on anything being merged back.

For context, the Japanese message to the mailing list got me thinking about language support; the font is ASCII only now and I don't think we can fit ç or é in a 5x5 square, let alone あ. There's plenty of other stuff tied up in that issue but it starts here.

**Comment by increpare** [comment]
I'm not worrying about non-A-Z characters for messages.  (I used up all my
worries about that playing about with arabic support).

**Comment by sfiera** [comment]
Title screen [1](https://www.dropbox.com/s/qscd5patdmmxr9i/message-1.png?dl=0) [2](https://www.dropbox.com/s/d9j1c9y0j84bk6f/message-2.png?dl=0) [3](https://www.dropbox.com/s/ku6gcjd4tvyqsxy/message-3.png?dl=0)
Message [1](https://www.dropbox.com/s/nf8eaogvmbsavqg/title-1.png?dl=0) [2](https://www.dropbox.com/s/fu2cuaikmmy2n02/title-2.png?dl=0) [3](https://www.dropbox.com/s/unpz610qxc8309n/title-3.png?dl=0)

Three pictures each: current font (1), new lowercase letters (2), all new letters (3). I think (2) is a definite improvement, though (3) starts to feel a bit bland.

Rectangular sprites were almost supported already—it only took 14 lines of code to get the rest of the way. Code in [sfiera/PuzzleScript:font](https://github.com/sfiera/PuzzleScript/tree/font).

**Comment by Draknek** [comment]
I would definitely be in favour of (3). Bland is a lot better than weird/hard to read.

FWIW, there's this font for pixel Japanese writing: http://akashicdesign.net/ja/88-zen/ though obviously with manually defined characters it's not actually practical to add as many characters as that.

**Comment by sfiera** [comment]
Bland is better than hard-to-read. I don't necessarily think it's better than weird! Weird fonts have character, and fitting capitals in 5x5 keeps the font in character for the engine. Do you find much difference in the readability of 2/3 or just the weirdness?

I think Arabic and Japanese are way out of scope right now (although the 5x5 katakana font on that site is interesting!). Latin-1 could be in scope, but if we want to talk about languages let's move to #212.

**Comment by increpare** [comment]
3rd one is most legible for me, fwiw.

**Comment by sfiera** [comment]
Full character sets:
http://www.puzzlescript.net/play.html?p=af39ffae5e027f34c00a
http://sfiera.github.io/PuzzleScript/play.html?p=af39ffae5e027f34c00a

**Comment by increpare** [comment]
guess this got done innit
