### ISSUE TITLE
Should norepeat_action be the default behaviour?

### ISSUE THREAD

**Issue by Draknek** [increpare/PuzzleScript#200]
Cute Train is the only game I can think of that actually makes use of the ability to hold down action.

More common is the case where this flag should have be set but hasn't been. (Understandable since it's a new addition, but also it's pretty easy to forget to set this type of prelude flag: I frequently forget to set `noaction` for example)

**Comment by increpare** [comment]
i'm going to give up on this dream. it's a good suggestion, and the right thing to do, but I'm not doing it. legaaacy

**Comment by Draknek** [comment]
You could add "norepeat_action" to the default initial game and the
examples?

That is kinda the same thing as defaulting it to being on, if people use
those as the base for their game

**Comment by increpare** [comment]
I want the default to be as simple as possible - I don't want there to be
all this stuff like you get with C++ where there's just a bunch of junk in
the header (though in practice there ends up being *some* finicky junk
there, I don't want to give the impression that there will be... :| )
