### ISSUE TITLE
Bug in editor for big files

### ISSUE THREAD

**Issue by eigenbom** [increpare/PuzzleScript#205]
There's a bug when editing large files. Some of the lines in the maps don't change colour and then I can't ctrl+click to load them. See the attached image, I can ctrl-click Level 15 but not Level 16.

Here's the code: http://www.puzzlescript.net/editor.html?hack=560c316fa080d00033d2

![image](https://cloud.githubusercontent.com/assets/1103761/2911323/df2295ea-d658-11e3-99c5-14e387ffbde7.png)

**Comment by increpare** [comment]
works for me now - i guess something magically fixed this in the past two years

**Comment by eigenbom** [comment]
Checked, works on Chrome / Win 10. :)

**Comment by increpare** [comment]
woo, thanks for checking!
