### ISSUE TITLE
Audio streams stop when sound effects play in firefox

### ISSUE THREAD

**Issue by dogman564** [increpare/PuzzleScript#209]
I was streaming http://somafm.com/play/groovesalad while playing http://www.puzzlescript.net/play.html?p=cffeb1b80f76458b742a

Sound effects after the start sound cause streaming audio to stop. 
This also happened with spotify web player.

This seems to only happen when playing puzzlescript games in firefox(chrome and safari are ok).

I'm using firefox version 29.0.1 on mac os x 10.9

**Comment by increpare** [comment]
can't repro this anymore? magically fixed?
