### ISSUE TITLE
"undo" command?

### ISSUE THREAD

**Issue by Draknek** [increpare/PuzzleScript#222]
There is a "restart" command but no "undo".

This would be potentially useful for games where you can die.

**Comment by Draknek** [comment]
Another usecase for having an undo command:
http://www.draknek.org/games/puzzlescript/train.php
http://www.puzzlescript.net/play.html?p=cffeb1b80f76458b742a

If you move back into the track/tentacle, you are in effect undoing the state. But if you press z, the path will actually get longer, because you're undoing the undo. It would perhaps be more intuitive/consistent if pushing back onto your path in these games just executed the built-in undo command.

**Comment by increpare** [comment]
hehehe, usability wise i agree that those games would be better if undo worked the way you describe. nice points :)

**Comment by increpare** [comment]
not adding for now, too special purpose.
