### ISSUE TITLE
Legend Conjunctions

### ISSUE THREAD

**Issue by rmmh** [increpare/PuzzleScript#227]
Having to pick a legend letter for every combination of objects is difficult and limiting.

I'm trying to write a game where I'd like to express one of 128 combinations for each cell, which is obviously too many to name explicitly.

Proposed syntax: use + to join to the previous cell. `p+e` in the legend means a cell with "p and e".

This could break the visual beauty of legends (stride mismatches), but they're basically unreadable for complex games anyways-- and whitespace could keep the formatting pretty.

**Comment by increpare** [comment]
I can see the utility of this, but it's pretty special use-case, and if you're going ugly, might as well go unicode-ugly as much as double-char ugly... . "No" to this suggestion for now. (But i appreciate it, and I feel your pain...)
