### ISSUE TITLE
Unhelpful error message if you call an object "message"

### ISSUE THREAD

**Issue by Draknek** [increpare/PuzzleScript#244]
Example:
`[ Player Message ] -> [ Player ] message hi`

Error:
`Name "hi", referred to in a rule, does not exist.
Error, malformed cell rule - was looking for cell contents, but found "hi". What am I supposed to do with this, eh, please tell me that.`

Too tired to make a minimal testcase, but it's simple enough.

**Comment by increpare** [comment]
Adding a warning not to call things 'message' earlier today. it'll do.
