### ISSUE TITLE
Attribution line not padded correctly

### ISSUE THREAD

**Issue by sfiera** [increpare/PuzzleScript#277]
If the attribution line "by ..." has lines of length 34 (the title width) then they're not indented right. You can see this in [The Great Emu War](http://www.puzzlescript.net/play.html?p=a6fcfa7742e88667c923).

The attribution should be wrapped to 33, or the -1 should be taken out of this line:
https://github.com/increpare/PuzzleScript/blob/master/js/engine.js#L227

(I'll look at this again later but I can't right now)

**Comment by increpare** [comment]
good catch

**Comment by increpare** [comment]
Cool, thanks for this.  It's lowish priority but I'll probably include it with the next proper update :)

Peace,

S

**Comment by increpare** [comment]
fixed now I think
