### ISSUE TITLE
Checkpoints can't be continued from title screen

### ISSUE THREAD

**Issue by increpare** [increpare/PuzzleScript#281]
Anna pointed out that she'd like this.  I think it'd be a good idea also.  

https://groups.google.com/forum/#!topic/puzzlescript/LQHQ2pDuI3U

**Comment by increpare** [comment]
It *should* be a matter of seeing where the checkpoint code is, serialising it, and adding special loading code to the continue function.

**Comment by JoeOsborn** [comment]
I think you could get stuck in a level if you don't also persist the whole undo stack, since it's usually possible to undo through checkpoints.

**Comment by Draknek** [comment]
You also need to deal with the possibility of the level changing between plays. Could cache a copy of the level at time of saving and throw out the savefile if it doesn't match at time of loading.

**Comment by increpare** [comment]
I'm basically ok with not dealing with that - people can just start a new
game or whatever.  Corruption already happens if people modify the game
(add new levels or whatever, and people end up skipping them when they
continue).  Not the end of the world.  but if it did deal with that I guess
it'd be ok.

**Comment by Draknek** [comment]
I dunno, skipping levels feels a lot less severe than someone reopening the
game and it's obviously glitched out.

I think it's not too much work to detect when this happens, anyway. If a
patch gets submitted that doesn't deal with this case, I'll happily add it
myself.

**Comment by increpare** [comment]
I'd accept a patch that just did the naive thing I suggested in the first comment.  Games breaking is ok, people can always restart a new game.  If a game breaks it breaks.

@JoeOsborn "I think you could get stuck in a level if you don't also persist the whole undo stack, since it's usually possible to undo through checkpoints."
Are there any puzzlescript games you know of that benefit from this?

**Comment by JoeOsborn** [comment]
I don't know any games off-hand that rely on undo through checkpoints, but imagine a game where you use up some resource to proceed ("Swapbot plus checkpoints"): you need three widgets to pass the last obstacle, the second to last obstacle could take four or five widgets, beating each obstacle sets a checkpoint, and you have seven widgets going into the second to last obstacle. If you did that one the inefficient way, you wouldn't have enough for the last obstacle. That's fine, undoing would get you back before the checkpoint so you could redo the second to last one, _unless_ you quit in between the last two obstacles, in which case you'd be stuck. Anyway it's a way to get stuck in a level, which has so far not really been possible in games with undo.

I think having "continue from checkpoint" and "continue from beginning of level" options at the title screen would be sufficient to avoid this problem, but I think it might be easier to store the undo stack along with the current level state. If neither of these is done, continuable checkpoints should probably be an option set in the header to avoid possibly breaking existing games.

**Comment by increpare** [comment]
gave a basic implementation a whack this evening. not totally trivial to hack it in...

**Comment by increpare** [comment]
test build of naive checkpoint restoring

http://ded.increpare.com/~locus/pstest/editor.html?hack=cf45e8ffd56d0e87f091

it's a bit hairy to implement, so if someone else could test it out for me, that'd be good. if nobody bites I'll upload it tomorrow and cross my fingers...

**Comment by Draknek** [comment]
The first time I tried it, trying to resume a game just gave a black screen.

But every subsequent time it has worked for me.

**Comment by increpare** [comment]
that might be because I just fixed it :P

**Comment by increpare** [comment]
(thanks for testing!)
