### ISSUE TITLE
Random outputs don't warn for overlap

### ISSUE THREAD

**Issue by sfiera** [increpare/PuzzleScript#284]
From a recent thread:
https://groups.google.com/forum/#!topic/puzzlescript/k231Ge40n8M

There's supposed to be a warning for overlapping objects:
https://github.com/increpare/PuzzleScript/blob/master/js/compiler.js#L1516

But if the current object is random, then we've already stopped looking at it:
https://github.com/increpare/PuzzleScript/blob/master/js/compiler.js#L1499

Probably, we should see a warning even for random objects—I would assume that, typically, when choosing from a set of objects, all objects belong to the same layer. (in the linked thread, it was just a single object, so "random" was superfluous and there's no evidence either way)

**Comment by increpare** [comment]
thanks for the bug report! : ) your suggestion makes sense.

**Comment by increpare** [comment]
thanks for this - I'm merging manually w/ some tweaks:)

**Comment by increpare** [comment]
oops responded to wrong thing. anyway. fixing this.
