### ISSUE TITLE
Don't use hasOwnProperty to detect ontouchstart 

### ISSUE THREAD

**Issue by increpare** [increpare/PuzzleScript#286]
turning #285 into its own bug to fix separately

**Comment by raggy** [comment]
I'm getting "ReferenceError: prefixes is not defined". "testStyles" isn't defined either, so I guess these are Modernizer-specific things?

Maybe we should just strip that part?

```js
Mobile.hasTouch = function() {
    return ('ontouchstart' in window) || window.DocumentTouch && document instanceof DocumentTouch;
}
```

**Comment by increpare** [comment]
yeah, just did that. trying to fix the checkpoint bug then I'll push this
live
