### ISSUE TITLE
Checkpoints don't work if there's an object named "checkpoint"

### ISSUE THREAD

**Issue by quat1024** [increpare/PuzzleScript#288]
The "Checkpoint" command doesn't work if there is any object named "Checkpoint", even if it's not used.

Here's a version of the example block pushing game that's _supposed_ to make a checkpoint every time you move the box, but the transparent object named "checkpoint" prevents that from happening... http://www.puzzlescript.net/editor.html?hack=225a6d4dd732f5dbd554

Can be an issue in flick/zoomscreen games where having a physical "checkpoint" object allows the player to press r and not start from square 1 (like in http://auntiepixelante.com/mansion/ for example)

**Comment by increpare** [comment]
good catch! :P
