### ISSUE TITLE
Cancel executes even if rules were re-applied after failing to move rigidbody

### ISSUE THREAD

**Issue by Terzalo** [increpare/PuzzleScript#300]
![2015-07-20 19 04 15](https://cloud.githubusercontent.com/assets/5587469/8780573/88bda712-2f12-11e5-9116-f0df971752e3.png)
As seen on the screenshot, the engine applies some rules, then figures out a rigidbody couldn't be moved and disables its rules. Related cancel command isn't called anymore, but the engine cancels the turn anyway.

**Comment by increpare** [comment]
Hey, big thanks for the report, especially about such a hairy area. Ufff.
Is this causing you problems right now? I can up the priority if so.

**Comment by JoeOsborn** [comment]
Is the fix here to clear the command list before a rigidbody-caused re-evaluation of the rules?

**Comment by Terzalo** [comment]
You're welcome!
It's not really causing problems for me, I'm just having fun playing with the engine :)
Anyway, seems like it could cause problems for someone, since it's not really obvious why rules aren't working like they should.

**Comment by increpare** [comment]
I haven't looked into it. Probably something like that, yep. (Or, not
clear, but revert to how they were before the rule group was applied).  As
you probably know a little bit, rigid stuff is haaairyballs.

note to self -  when fixed (whether me or someone else), add extra test
cases to cover - commands applied before, commands applied after, and
commands applied during.

**Comment by increpare** [comment]
> Is the fix here to clear the command list before a rigidbody-caused re-evaluation of the rules?
I tried this and uploaded. However I don't know if it works or not because I couldn't make a repro case.

Wish I had asked for an example of this.  My head's a bit fuzzy about rigid rules right now, and I can't construct an example...

**Comment by increpare** [comment]
I uploaded a possible 'fix' to puzzlescript.net. If anyone can construct something that still has this terrible behaviour please do!
