### ISSUE TITLE
Suggestion: "noundo" command to exclude a turn from the undo history

### ISSUE THREAD

**Issue by Draknek** [increpare/PuzzleScript#301]
I think this is only relevant for realtime games, but maybe there are other use cases.

In my current game, you can push a stone and it will keep moving, but I use realtime_interval rather than again so that the player isn't prevented from moving.

However, if you push a stone, and move around while the stone is moving, then undo, you can undo to a state in the middle of the stone's movement which feels very weird.

I propose a new command "noundo", which means "don't add anything to the undo history this turn". Then I'd be able to make it so that pressing undo would take you back to the state before pushing the stone. Hopefully that makes sense!

If I were to add code for this, would it be likely to be accepted?

**Comment by increpare** [comment]
thanks for the report alan 

>If I were to add code for this, would it be likely to be accepted?
Nope.  I don't feel that this is especially unnatural in the case you give, and it's a bit fiddly as options go.
