### ISSUE TITLE
alan reports random stalling of editor

### ISSUE THREAD

**Issue by increpare** [increpare/PuzzleScript#302]
might possibly be something to do with 

  var hasCopyEvent = (function() {
    var e = elt("div");
    if ("oncopy" in e) return true;
    e.setAttribute("oncopy", "return;");
    return typeof e.oncopy == "function";
  })();
but I don't think so.

**Comment by increpare** [comment]
something to do with touch screen fucking it up (codemirror bug, or mine?)

**Comment by increpare** [comment]
closing because I can't repro.  i should've recorded more info about browser/os when i logged this the first time...

**Comment by increpare** [comment]
@Draknek poking, just in case you've anything to add

**Comment by Draknek** [comment]
Probably would have been Chrome on Windows, but I don't recall anything about what this was about
