### ISSUE TITLE
If I make a move which due to "again" resets everything, a null change is added to the undo stack

### ISSUE THREAD

**Issue by increpare** [increpare/PuzzleScript#315]
await test case from alan

**Comment by Draknek** [comment]
http://www.puzzlescript.net/editor.html?hack=4bf31d9b04606fb756a8e142a0fceeae

Move towards the box from the left side and you get pushed back. Nothing has changed, but it adds an undo state

**Comment by increpare** [comment]
Should be fixed now, thanks for the report :)  (may need a force-refresh)
