### ISSUE TITLE
camera wrong/level display getting messed up

### ISSUE THREAD

**Issue by increpare** [increpare/PuzzleScript#324]
Yes. After the game says Good Morning World
walk south and stand next to the dog.

The next scene will not look correct because the player has to walk far south, moving the camera, and the following scene has no player

http://www.puzzlescript.net/editor.html?hack=3c6338236b03988c2da9c4abd2c54ef6

**Comment by increpare** [comment]
solution is to mandate level data be rectangular

(smaller repro here:
http://www.puzzlescript.net/editor.html?hack=e9dab8ba3c5bf75e25e852c2cadc9ab9
)

**Comment by ColtonPhillips** [comment]
Adding a warning about non rectangular levels doesn't fix the bug. Here is a version of the source code with pure rectangular rooms and the bug exists:
=================================
Successful Compilation, generated 439 instructions.
GitHub submission successful - link to source code:
http://www.puzzlescript.net/editor.html?hack=1433a0eae8bce4808b31a5ba6d6676fc
The game can now be played at this url:
http://www.puzzlescript.net/play.html?p=1433a0eae8bce4808b31a5ba6d6676fc

**Comment by increpare** [comment]
http://www.puzzlescript.net/editor.html?hack=1433a0eae8bce4808b31a5ba6d6676fc

**Comment by increpare** [comment]
May take a page refresh, but should be good now. Let me know if it's still acting up.
