### ISSUE TITLE
gif export doesn't work on IE10

### ISSUE THREAD

**Issue by increpare** [increpare/PuzzleScript#333]

**Comment by increpare** [comment]
idgaf

**Comment by increpare** [comment]
(i don't have ie right now - if someone else can fix/whatever it, then I'll look into it)

edit: or was it shortcut related? i can't remember. might as well leave it open.

**Comment by quietshu** [comment]
The editor is completely broken in IE11 -_-

![2](https://user-images.githubusercontent.com/3676859/41460689-16ac0d1a-70c0-11e8-95de-23cd69bf7df7.PNG)

**Comment by increpare** [comment]
ah, this is my use of Object.assign.  I guess I should use something else...

**Comment by increpare** [comment]
fixed by #542

**Comment by increpare** [comment]
Oh wait, probably not fixed, but also I probably am ok with dropping support for IE10 for this one feature.
