### ISSUE TITLE
some unicode characters can be set in legend but not used in map 🔒 🔐

### ISSUE THREAD

**Issue by increpare** [increpare/PuzzleScript#334]
http://www.fileformat.info/info/unicode/char/1f512/index.htm
http://www.fileformat.info/info/unicode/char/1f510/index.htm

**Comment by david-pfx** [comment]
It would be really helpful to define exactly which characters are acceptable for object names and glyph characters.

**Comment by increpare** [comment]
It's not exactly a duplicate of #518, but they're the next frontier in this task.  Emoji grapheme recognition is awfully complex to do.  I don't expect at any point in the future to have precisely specified what are acceptable object/glyph names in any canonical fashion.  

(But today I did expand the possibilities a lot with allowing other unicode sequences. Just not in the direction of emoji.)
