### ISSUE TITLE
Comments don't work inside of rules

### ISSUE THREAD

**Issue by ncrecc** [increpare/PuzzleScript#367]
![](http://image.prntscr.com/image/24d1cfed02044585bd5052e20e684cfa.png)

**Comment by increpare** [comment]
Uff. this might be hairy to fix. I don't view it as being super important, so I may ignore it for the time being.  HOWEVER, thanks for reporting it.

**Comment by increpare** [comment]
wait no

**Comment by increpare** [comment]
i can patch this to get your example to work, but then other examples don't work. I don't want to half-ass it, so undoing the change and leaving this open.

**Comment by ThatScar** [comment]
wait, can't you just delete all comments during compilation start?
sounds like an easy fix to me

**Comment by ncrecc** [comment]
That would be bad if any messages in the game have parentheses in them.
