### ISSUE TITLE
+ is reported as a keyword, even though it's not?

### ISSUE THREAD

**Issue by Draknek** [increpare/PuzzleScript#371]
Unless I'm having a sleep-deprived moment, + isn't a meaningful character, but it now gives the error "You named an object "+", but this is a keyword. Don't do that!"

Caused by #338

I am of the opinion that these characters should be allowed as synonyms but not as the original name for an object. < > ^ v | are all useful characters for maps!

**Comment by increpare** [comment]
it means something in rule groups, though? but you're right, maybe that's a bit too much - there's no room for ambiguity because they're used in different contexts

[a]->[b]
+ [c]->[d]

**Comment by increpare** [comment]
rolled the change back.

**Comment by increpare** [comment]
"I am of the opinion that these characters should be allowed as synonyms
but not as the original name for an object. < > ^ v | are all useful
characters for maps!"
i agree that they're useful. however, messes can also be caused that can be
awkward to explain. so IDK O_O

**Comment by Draknek** [comment]
Maybe just ban "v"? I can see myself accidentally naming an object that and
trying to use it in rules, but the others are really really awful object
names in ways that are self-evident.
