### ISSUE TITLE
Infer rule output

### ISSUE THREAD

**Issue by ThatScar** [increpare/PuzzleScript#372]
Maybe something you can include in the prelude that makes the rules automatically infer the input to the output

For example:
[ > Box | Box ] -> [ > Box | > Box ]
would become
[ > Box | Box ] -> [ | > ]
or
[ > Box | Box ] -> [ | > Box ]
or
[ > Box | Box ] -> [ . | >. ] (worst case)
or whatever, you name it. I think everything would be possible with just ommiting stuff.
To delete something, just write
[ > Box | Abyss ] -> [ No Box | ] (note that this doesn't delete the abyss)

Potentially saves a non-negligible amount of time.

**Comment by increpare** [comment]
looks ambiguous/confusing to me. 

(thanks for the suggestion, though).

**Comment by ThatScar** [comment]
I'm not sure what looks so alien to you, it just allows you to only write the changes.

This is the original You're Pulleying My Leg rules compared to what the rules could be (I most likely made some mistakes, though, can't test it, obviously):
https://www.diffchecker.com/RhuPoDiP
You're Pulleying My Leg is actually very light on the rule length, I'll find a better example later.

I really like how the rules only expose the changes done, don't you? There are probably way better examples where you relieve a lot more copying. I don't think it adds any friction nor does it hinder readability if the reader knows it's this other style (which is the only real problem I see here).

You could compile this syntax to the current syntax, so that's what I am thinking of. Check if there's stuff in the prelude and change the code in the memory accordingly, pretty much how it already does with the relative <>v^.
I would gladly implement this myself if you cooperated a bit.

**Comment by increpare** [comment]
>I really like how the rules only expose the changes done, don't you?
Not really.  (though I understand horizontal space requirements get a bit silly for fancier rules and this would help that a bit).

This would change the semantics of existing games also, which isn't allowed. (and I don't think having a keyword in the prelude to turn it on or off would make this better).

>I would gladly implement this myself if you cooperated a bit.
I am unlikely to cooperate on this particular task.

**Comment by ThatScar** [comment]
That's fine, I'll fork it and figure it out myself some time.
I'm thinking of making it clear to the user that this is a different language or it's a no-go. Changing the colors should achieve most of this.

**Comment by Draknek** [comment]
FWIW, I don't think this is a change that should be made now but if you were starting over from scratch it would definitely be more pleasant to write games if I didn't have to keep repeating myself on the RHS.

(The benefit isn't in the end result being clearer, it's in editing rules being faster/less frustrating/less bug-prone.)
