### ISSUE TITLE
2D rules

### ISSUE THREAD

**Issue by ThatScar** [increpare/PuzzleScript#373]
Let's face it, making stuff work diagonally is difficult. Maybe something whitespace-neutral like this?
Late [
[ Knight | ]
[ | ]
[ | Player ]
] -> [
[ | ]
[ | ]
[ | Knight Blood ]] message you lost

**Comment by ThatScar** [comment]
Obviously, there are also some rotational problems to fix and I'm thinking of RotateOnly or Unflippable or some bit flags you put among all the Left, Vertical and similar stuff you put before rules.

**Comment by increpare** [comment]
Any example games you'd like to make?

I don't find your notation readable. I'd be more amenable to adding diagonals before full 2d support, like upleft/upright/downleft/downright as direction-specific keywords - 

but even then, what games would make use of them?

**Comment by ThatScar** [comment]
I have some ideas but practically knights are probably where it ends, just some spontaneous idea. Diagonals still would be useful in a lot of cases. You can close it.

**Comment by increpare** [comment]
so understanding - thanks!
