### ISSUE TITLE
Empty message bug

### ISSUE THREAD

**Issue by ThatScar** [increpare/PuzzleScript#376]
Empty message in rules doesn't bring up any dialog but wins the level when you press action.
This is all you need to win any level in any (hacked) game that has a wall:
[ > Player | Wall ] -> message
If require_player_movement is set, you need this instead:
[ > Player | Wall ] -> [ Player | Wall ] message
http://www.puzzlescript.net/editor.html?hack=939bad61addffa860ec6c64411383474
You obviously can do the exact same with just "win" instead of "message" but it seems odd that this works like it does.

**Comment by increpare** [comment]
wait closed wrong bug

**Comment by increpare** [comment]
fixed now https://github.com/increpare/PuzzleScript/commit/4e5eddb56f640088ad67b2e4b5c5ac15ffd9bc09
