### ISSUE TITLE
Comments in rule messages

### ISSUE THREAD

**Issue by ThatScar** [increpare/PuzzleScript#377]
Comments behave weirdly in messages:
http://www.puzzlescript.net/editor.html?hack=9f1c275334321d207fd667d570e72ad8
It seems to delete everything in a rule message that goes after the "(" character.
The messages between levels work just right with parentheses, not detecting any comments (I don't think there's any reason to do comments in messages, so that's good).

**Comment by increpare** [comment]
should be good now
