### ISSUE TITLE
Tapping the game pane on a touchscreen laptop breaks keyboard input

### ISSUE THREAD

**Issue by Draknek** [increpare/PuzzleScript#380]
In editor, tap the upper-right pane where the game goes. This gives it a grey border and the game no longer responds to key presses

**Comment by increpare** [comment]
somebody asked that I enable touchscreen controls  (which have slowly become a bit moth-eaten) in the editor so they could fiddle with things on an iPad.  I should probably disable it again until it's working?

**Comment by Draknek** [comment]
It's fine to have touchscreen controls! They just shouldn't disable the keyboard controls

**Comment by increpare** [comment]
is this fixed now?

**Comment by Draknek** [comment]
Nope - still misbehaving in this way.

**Comment by increpare** [comment]
I've done a bunch of stuff to get the puzzlescript editor working on ipad.  This should be fixed. It's not live now but I'll put it live tomorrow.
