### ISSUE TITLE
Can lose WIP levels by accidentally completing them

### ISSUE THREAD

**Issue by Draknek** [increpare/PuzzleScript#381]
If I'm editing a level, then accidentally complete it while the palette isn't open, the game goes to the next level and the wip level is lost.

Suggestion: when a level is completed, print the level contents to the console (contents of the state you'd reset to, not the state you're in at completion)

**Comment by increpare** [comment]
I hope you didn't lose something annoying.  In most cases that'd be console
spam.  Hm. How about whenever you close the editor it prints the map to the
console?

**Comment by increpare** [comment]
>I hope you didn't lose something annoying.
you know what I mean. annoying/important.  sleepy right now.

**Comment by increpare** [comment]
or maybe allowing people to undo past level boundaries (if only in the
editor) would be enough in this case!

**Comment by increpare** [comment]
(but that might be bad because if you undo too far you could also lose a
level...)

**Comment by Draknek** [comment]
Haven't lost anything because of this recently fortunately!

I am a-okay with printing to the console when you close the editor - that might also be useful in times when I want to remember what a previous version of the level was like
