### ISSUE TITLE
Restart after message

### ISSUE THREAD

**Issue by ThatScar** [increpare/PuzzleScript#382]
It's an extremely rare case but it would be nice to be able to restart right after reading a message.

**Comment by increpare** [comment]
Could you give me a use case?

**Comment by ThatScar** [comment]
That Zelda torch game had a "Game Over" after a long explosion. When you've pressed X to continue, it's just a screen full of explosions until you press R.

**Comment by increpare** [comment]
I don't find that compelling/worth catering for.

**Comment by Draknek** [comment]
You should be able to do something like this:

[ restartflag ] -> restart

[ player spikes ] -> [ player spikes restartflag ] message Game Over

[ restartflag ] -> again

(Not tested but something like that should work)

**Comment by ThatScar** [comment]
Fun fact, in that Zelda game, the explosion overwrites the Player, so there isn't one when you want to restart :D
