### ISSUE TITLE
Playing games on a phone - can't swipe down without reloading page

### ISSUE THREAD

**Issue by Draknek** [increpare/PuzzleScript#383]
Not sure how long this has been the case - it definitely used to work

Android 6, chrome

**Comment by ThatScar** [comment]
I can confirm, I've managed to move down by not releasing my finger and moving it back up a little after the player moved but it's evidently not focused on the game anymore, like it used to be (I can now even pan the page to scroll down)

**Comment by increpare** [comment]
poking @andrew-cantina for mobile bugs in case he has interest in following them up

**Comment by ThatScar** [comment]
But it was somehow broken by your commits, right? I don't see anyone else's commits in the past several months.

**Comment by increpare** [comment]
Andrew cantina originally did the mobile stuff.  I haven't knowingly touched the mobile input code, so I thought I'd poke him to let him know, just on the off chance he's interested (it's been a long time, so it's unlikely he is, but I do recall him ages ago expressing an interest in further maintenance work on his stuff).  

>But it was somehow broken by your commits, right? 
It's not certain at all that I broke it.  Sometimes stuff just breaks.

If you want to go back through older versions to see if you can find what change, if any, caused this bug, be my guest. (I'd advise starting at the last version @andrew-cantina submitted + doing a binary search).

**Comment by Draknek** [comment]
Fix might be as simple as adding some code from here: http://stackoverflow.com/questions/29008194/disabling-androids-chrome-pull-down-to-refresh-feature

**Comment by increpare** [comment]
feel free to poke me on Thursday about it :P

**Comment by smattiso** [comment]
I've actually discovered a workaround for this. You can disable the feature in mobile Chrome.
http://help.centralreach.com/?p=8816

If you want PuzzleScript games to be a 'special case' however, here's some JavaScript to support that.
https://stackoverflow.com/questions/29008194/disabling-androids-chrome-pull-down-to-refresh-feature

**Comment by Draknek** [comment]
That's good to know about, but I was looking for a solution that'll work for all players not something that you have to manually change to make it work.

Investigated this today! The above link doesn't work any more, but what does work is applying the css style "touch-action: none" to the game container.

**Comment by ThatScar** [comment]
Anyone cares to make a pull request? Personally, I'm not too irritated by my haphazard solution [Action Player] -> [Down Player] right now and I don't have a fork of puzzlescript but if it takes you very little effort to make a pull request, it would be really appreciated. (if you know a better solution than making a PR for Stephen, anything works and I'm all ears)
Please reply if you won't make a PR, I will do it myself sometime, in that case.

**Comment by increpare** [comment]
should be fixed now if you refresh? (test and let me know - i don't android)

**Comment by Draknek** [comment]
Yup, all good :)
