### ISSUE TITLE
Logging performance issues after toggling editor

### ISSUE THREAD

**Issue by ThatScar** [increpare/PuzzleScript#384]
Normally, when verbose_logging is on, command executions are concatenated with the execution count written:
Rule 633 applied. (x17)
But when you enter/exit the level editor, it instead types it 17 times and there's a performance spike, which is pretty serious when you have over 50 executions. Rebuilding the code, both when the editor is on and when it's not, fixes the issue but it breaks again when you toggle the editor.
The performance is unaffected if verbose_logging is off.

**Comment by increpare** [comment]
Oh, I fixed this this week or last week.  Also, apologies for the slight delay in getting back.
