### ISSUE TITLE
Realtime?

### ISSUE THREAD

**Issue by harrycode** [increpare/PuzzleScript#386]
Hi, I have a problem in which I want something to move automatically as if it was an enemy trying to push the player, but I don't know how! Please help!

**Comment by increpare** [comment]
Ask on the mailing list - https://groups.google.com/forum/#!forum/puzzlescript - someone might be able to guide you in the right direction.  This is just for bugs.

**Comment by harrycode** [comment]
Oh ok thanks! :D
