### ISSUE TITLE
Pixels aren't crisp

### ISSUE THREAD

**Issue by Draknek** [increpare/PuzzleScript#391]
Pixel edges are blurry which is generally not noticeable but I'm reporting it because sometimes it bugs me

Chrome 58.0.3029.110

**Comment by increpare** [comment]
yeah not crips anywhere i can find either.  make note to look into 


https://developer.mozilla.org/en/docs/Web/CSS/image-rendering 
or https://developer.mozilla.org/en-US/docs/Games/Techniques/Crisp_pixel_art_look

"-ms-interpolation-mode: nearest-neighbor" does better than "-webkit-optimize-contrast" which i might use elsewhere.  this might
