### ISSUE TITLE
sound glitches out after a while

### ISSUE THREAD

**Issue by eyesack** [increpare/PuzzleScript#404]
I tried to make a drum sequencer in puzzlescript:

http://www.puzzlescript.net/play.html?p=60f2ffb284e2a3e197ce2ca51e5f9734

It starts out fine, but after a minute or two the sound will get gradually more and more distorted, and eventually not play at all. (This is in Chrome on a Mac.)

I realize I'm trying to make puzzlescript do something it was probably never intended to do...

**Comment by ncrecc** [comment]
No, I think this happens on all games.

**Comment by increpare** [comment]
could you force reload the page, try again and let me know if it's fixed?

**Comment by eyesack** [comment]
It fixes the problem temporarily, but it still glitches out eventually. It might be my imagination but it seems to take longer to glitch out now?
Also, the 3 browsers I tested all seem to show slightly different behavior.
Chrome: works perfectly for a while, then glitches out
Firefox: doesn't glitch out, but realtime_interval sometimes seems unsteady
Safari: doesn't glitch out, but realtime_interval is inexplicably slower

**Comment by increpare** [comment]
I'm going to kind of magically assume that this isn't a problem any more (I can't repro it right now).  If it is, lemme know.

Apolgoies for...the slight delay in getting back to you.
