### ISSUE TITLE
Enhancement request: display level number

### ISSUE THREAD

**Issue by thSoft** [increpare/PuzzleScript#408]
Sometimes, knowing the number of the current level can be useful to the player. It would be great if it was displayed either:
* always
* if a flag (e.g. show_level_number) is present in the prelude

**Comment by increpare** [comment]
I agre it would be useful for some people. But where to display it?

**Comment by thSoft** [comment]
Maybe below the name of the game, center-aligned, with smaller font?

**Comment by david-pfx** [comment]
A level name that could be set in the script might be more useful. If set, it should display centered top (or bottom)

**Comment by thSoft** [comment]
Yes, I think that would be even better!

**Comment by smattiso** [comment]
Agreed, @david-pfx, level numbers can be arbitrary depending on whether you count message screens as levels, and there might be a use case either way. A string, meanwhile, can represent digits as well as text.
The only difficulty then becomes; how do you show that text? What font do you use, and how do you align it? Some games already utilize the 5x5 pixel tiles to draw their own digits which they then place on the map on a new collision layer. This works when your levels are numbers, but becomes unwieldy if you want an entire font.

**Comment by increpare** [comment]
I think I'm ok with it as is for now (though I understand there are tradeoffs).  Thanks for the feedback everyone.
