### ISSUE TITLE
Bug: "norestart" prelude option can interfere with "restart" command

### ISSUE THREAD

**Issue by Draknek** [increpare/PuzzleScript#411]
http://www.puzzlescript.net/play.html?p=9484988

Normal behaviour: move until you run out of energy, level rules will use "restart" command to reset.

Bug: press R, then run out of energy. Nothing happens when you press R, but nothing happens when you run out of energy either. The game is permanently locked up until you reload the webpage.

**Comment by increpare** [comment]
ufff...feel free to poke me about this if I don't get around to it...need to make a simple test case first...

**Comment by increpare** [comment]
With my apologies for the minor delay.
