### ISSUE TITLE
(Enhancement) Add 'TESTS' section to PuzzleScript files

### ISSUE THREAD

**Issue by richlocke87** [increpare/PuzzleScript#412]
It'd be really useful to be able to add test cases to PuzzleScript files. It would give much greater confidence that rule changes haven't broken anything. Something like:

```
=======
TESTS
=======

test that crates can be pushed right

given
.....
.pc..
.....

when [right 0.1 right]
then
.....
...pc
.....
```

This could be further enhanced, of course, but a basic before-and-after system with the ability to simulate keyboard input would be a great start.

A new 'TEST' link in the editor would run all tests found in the TESTS section and print results to the console.

**Comment by richlocke87** [comment]
I'm going to start looking at this but wanted an issue to track work against.

**Comment by increpare** [comment]
This is way outside the scope of complexity that I want to support (and I feel like it's not crazy useful - though I haven't made very big games w/ puzzlescript).  (Feel free to do it in a branch of your own, of course!)

**Comment by richlocke87** [comment]
Ah, sure, I'd do it in a separate branch, then you can see what you think of it. It won't be useful for everyone, but it'll definitely help with my dabblings - currently I pretty much have to run through the whole game to make sure everything still works. Being able to do that at the click of a button is a much more attractive prospect!

**Comment by increpare** [comment]
understood!  There's already a unit testing system for the engine - if you
play a game in the editor and press ctrl+j it spits replay info to the
console - that you can paste into tests/resources/testdata.js and run with
tests/index.html. But that's for fixed source code. But it might be a
starting point (though it's not very 'code-integrated') - dunno!

**Comment by richlocke87** [comment]
Oh, interesting! Thanks - this is definitely useful to see. Simulating inputs and stuff - good to see how that's done. And some of those test names are inspired. "Damn I'm huge" is a particular highlight.

Yeah, this isn't all that far from what I want to do. Time to get coding!
