### ISSUE TITLE
allow newlines in rules

### ISSUE THREAD

**Issue by increpare** [increpare/PuzzleScript#417]
```[ no c | >c | c | no c ] ->
[ no c | c | >c | no c ]

[ no c | >c | c | c | no c ] ->
[ no c | c | c | >c | no c ]

[ no c | >c | >c | c | no c ] ->
[ no c | c | >c | >c | no c ]
```

looks so much better than

```[ no c | >c | c | no c ] ->[ no c | c | >c | no c ]

[ no c | >c | c | c | no c ] ->[ no c | c | c | >c | no c ]

[ no c | >c | >c | c | no c ] ->[ no c | c | >c | >c | no c ]
```

**Comment by david-pfx** [comment]
I agree, and right after the arrow is both safe and easy to parse.

**Comment by increpare** [comment]
nah it's slightly more involved than I thought (how do you know when you've come to the end of a rule? when your patterns are balanced and get to something that isn't a command); I'm (Still) not interested in supporting it right now, so closing
