### ISSUE TITLE
Sound issue on Chrome for Windows

### ISSUE THREAD

**Issue by samanthaeschaffer** [increpare/PuzzleScript#419]
I've been working on a game the past couple of days and when I went to add sound, I realized that the editor wasn't playing anything. I exported the game and ran the game on its own and still no sound. After trying all the obvious user error solutions (computer muted? headphones plugged in? etc), I noticed this warning in the console:
> An AudioContext in a cross origin iframe must be created or resumed from a user gesture to enable audio output.

I opened up a friend's game on itch.io that I know was also made in PuzzleScript and sure enough, still no sound and the same warning.

If I refresh and as it's loading click on the page fast enough, I can get it to load without the warning and sound successfully plays.

Adding `console.log(AUDIO_CONTEXT.state)` after the [AudioContext  constructor](https://github.com/increpare/PuzzleScript/blob/master/js/sfxr.js#L19) shows the state as `suspended` when the warning appears and `running` when I manage to click fast enough and the warning doesn't appear.

I tried just adding `AUDIO_CONTEXT.resume()` in a click event, but even though the console logged that it successfully transitioned from `suspended` to `running`, there was still no sound. Javascript isn't really in my wheelhouse, so it's very possible I missed something in my quick hacky fix attempt.

Browser is Google Chrome (`Version 63.0.3239.132 (Official Build) (64-bit)`).
Platform is PC (Windows 10).

Lemme know if I can provide any more info to help.~

**Comment by increpare** [comment]
Thanks for letting me know about this.

Ah, so the problem is that it's broken when a puzzle script game is
embedded itch.io?  Could you link me to a page that has this error?

S

2018-01-08 12:32 GMT+01:00 Samantha Schaffer <notifications@github.com>:

**Comment by samanthaeschaffer** [comment]
From what I can see, it's broken pretty much everywhere?

### Editor
There's also an unrelated bonus unsafe script error.

![puzzlescript-issue419-editor1](https://user-images.githubusercontent.com/3683085/34711971-29e2556c-f571-11e7-8e03-7626e3f4e3b4.png)

### Exported Local File
![puzzlescript-issue419-exported1](https://user-images.githubusercontent.com/3683085/34712018-525d858e-f571-11e7-8554-f1516c42e9bd.png)
![puzzlescript-issue419-exported2](https://user-images.githubusercontent.com/3683085/34712019-528f5fe6-f571-11e7-925e-5ea9ab1965f9.png)

### Embedded
[Link to the game pictured.](https://hypernexus.itch.io/exploding-barrels) Interestingly if I go into settings on itch.io and enable `Require a click to run HTML5 game embeds` (pictured below), the warning doesn't appear and sound plays normally.

![puzzlescript-issue419-embedded1](https://user-images.githubusercontent.com/3683085/34712178-e0d07114-f571-11e7-9fe7-6a30b1eade3f.png)
![puzzlescript-issue419-embedded2](https://user-images.githubusercontent.com/3683085/34712179-e1057800-f571-11e7-82cf-6a1a50038949.png)

Would it be possible to initialize the AudioContext in response to the game starting (eg the first user input) rather than immediately on load?

**Comment by samanthaeschaffer** [comment]
That didn't quite fix it, but playing with the code in the exported html file, I found that the following change to that method you added `checkAudioContextExists` does~

```javascript
function checkAudioContextExists() {
    try {
        null == AUDIO_CONTEXT && ("undefined" != typeof AudioContext ? AUDIO_CONTEXT = new AudioContext : "undefined" != typeof webkitAudioContext && (AUDIO_CONTEXT = new webkitAudioContext))
        if(AUDIO_CONTEXT != null && AUDIO_CONTEXT.state == "suspended") {
            AUDIO_CONTEXT.resume().then(function() { 
                window.console.log("Resumed AudioContext")
        });
        }
    } catch (e) {
        window.console.log(e)
    }
}
```

The problem was that `AUDIO_CONTEXT` wasn't null; it was just in the suspended state, preventing it from playing sound.

Lemme know when that goes live on the editor, and I'll be able to confirm that it's fixed.~

**Comment by increpare** [comment]
I think this is all good now
