### ISSUE TITLE
Some games in GitHub release do not compile with current compiler

### ISSUE THREAD

**Issue by david-pfx** [increpare/PuzzleScript#421]
I found collapse, dropswap, manic_ammo, ponies_jumping, robotarm, twolittlecrates3 and 4 with errors (duplicate glyph, and/or errors), but there could be others.
Edit: cratopia has multiple errors.

**Comment by increpare** [comment]
They all compile now (I think since you posted this helpful message I made error messages more lenient in the case of historically-undetected errors).  The errors are left there - they don't stop compilation, and the games, I haven't check them too closely, but seem to work.

**Comment by increpare** [comment]
(apologies for taking a while to get around to this)

**Comment by david-pfx** [comment]
Good to hear from you. 3 years must be some kind of a record! New computer and I don't have any of that stuff at hand to check it out, but sounds fair enough. Cheers!
