### ISSUE TITLE
Implement mouse actdions

### ISSUE THREAD

**Issue by david-pfx** [increpare/PuzzleScript#422]
New feature: Implement two new events, for left and right mouse click (or short/long press).

Clicking on an object adds that object to the move list (but the object will not actually move). A rule can reference the object and event (in the same way as Left or Action) to take any desired action, such as destroy the object, make a sound and so on.

Opens up a whole new class of interesting puzzles.

**Comment by increpare** [comment]
I don't personally think PS is reactive enough to work well with mouse-based games.  Overall mouse based games need a different approach I think. And there's weirdness with the differences between mouse and touch based input.  You could try to make a PS-like aimed exclusively at touch-input and probably make something nice, but the existing one doesn't deal with it very well, is my opinion, and can't be easily modded to do so.

someone else made a fork that supports mouse input if you want to try it out - https://groups.google.com/forum/#!topic/puzzlescript/FTqxzGcOD5Y

best :)

S
