### ISSUE TITLE
Directive to stop music after one play

### ISSUE THREAD

**Issue by Ayelis** [increpare/PuzzleScript#424]
There should be a way to stop music after one playthrough. Sometimes a soundtrack gets annoying, and it's better to just stop. Sometimes the music was just for the introduction, and you don't want it looping. To this end, there should be a way for the interpreter to have the music stop instead of loop.

Something like `noloop_music` ought to work.

**Comment by Ayelis** [comment]
It might also be nice to have a `stop_music` action, so the theme music can be stopped when the game starts.

**Comment by increpare** [comment]
Youtube embedding is a weird side-feature that I don't want to support too much.  ( It keeps on breaking, creates external dependencies, and also gives people an outlet for considerable expenditure of energy that isn't directly mechanical-game-design-focussed (one of the goals of the engine is to keep the focus on puzzle designy parts of game making) )

**Comment by increpare** [comment]
(suggested work around: upload a file with a large silent pause at the end)

**Comment by Ayelis** [comment]
I've fixed this issue on my repo. I didn't intend for it to show up on your page. Sorry! :fearful:

**Comment by Ayelis** [comment]
Wait, am I to understand that I broke Playlist Functionality when trying to get the music to stop repeating twice? :open_mouth: I didn't even know PuzzleScript supported Playlists! Now I think there should be a directive regarding whether the youtube ID references a playlist or a single video, otherwise the video thinks it's in a playlist and plays twice. :+1:
