### ISSUE TITLE
Rule to play new music

### ISSUE THREAD

**Issue by Ayelis** [increpare/PuzzleScript#425]
Music should be swappable on the fly, after any certain rule has fired off. In this way, an event can be made to change the audio to a new track.

Something like:
`[Player DungeonEntrance|Threshold] -> [DungeonDoorClosed|Player Threshold] youtube Ra87zzaIL1s`

Another use case might exist for sound effects which do not stop the music:
`[Player Talisman][Inventory1] -> [Player][Inventory1 Talisman] youtube_once cU1VFErmUGA`

**Comment by increpare** [comment]
Nope. Don't want to integrate youtube support so much into the engine.  It's a bit hard to maintain.
