### ISSUE TITLE
Suggestion: sfx should only play after the parser's finished going through all of the rules

### ISSUE THREAD

**Issue by ncrecc** [increpare/PuzzleScript#429]
https://www.puzzlescript.net/editor.html?hack=588a818d44cf145cf569e489b303d172

**Comment by increpare** [comment]
Thanks for the suggestion.

I'm happy with it being linked to the mid-turn process.  But I see your point.  (It'd be messy to implement because I'd need to check that any new objects were't the result of a 'move')
