### ISSUE TITLE
Rule generates "INVALID" without a warning.

### ISSUE THREAD

**Issue by ThatScar** [increpare/PuzzleScript#432]
[This game right here](https://www.puzzlescript.net/editor.html?hack=ff8f6ff3d2880ea1a46f48a684c8fe2c)
has a rule on line 104 that generates the word "INVALID" instead of a direction. This is probably fine but it should give an error instead of silently failing.

**Comment by increpare** [comment]
ah cool - someone found an in-the-wild reproduction of
https://github.com/increpare/PuzzleScript/issues/427 .  Cool. I'll deal
with it at some point.  Hope it didn't cause you much trouble.

Best,

S

2018-02-22 14:51 GMT+01:00 ThatScar <notifications@github.com>:

**Comment by increpare** [comment]
(other bug is long fixed)
