### ISSUE TITLE
Exported games don't run on mobile

### ISSUE THREAD

**Issue by Draknek** [increpare/PuzzleScript#439]
Hack the Net (on puzzlescript.net): https://www.puzzlescript.net/play.html?p=8b5eb39cb825277832d261b3142f084b works
Hack the Net (exported today): http://www.draknek.org/misc/Hack-the-Net.html doesn't work

The title screen appears, but it doesn't respond to any input.

This is on my Android phone with Chrome 66.0.3359.126. I've seen this problem with other games too, e.g. https://marcosd.itch.io/sleepy-players

**Comment by quietshu** [comment]
Seems `Mobile.enable()` ([here](https://github.com/increpare/PuzzleScript/blob/5936aceb438f4d37ba5d8522c9265a36ed597ee8/play.html#L312)) is not being called in exported HTML. I'd like to file a PR to fix.
