### ISSUE TITLE
Don't show mute button if a game doesn't have any sounds/music

### ISSUE THREAD

**Issue by Draknek** [increpare/PuzzleScript#449]
E.g. https://www.puzzlescript.net/play.html?p=0e692c47ab0b18099c2485d644590b4e

This game has no sound effects and no youtube URL, so will never play any audio. It's weird that it still has a mute button.

**Comment by increpare** [comment]
makes sense!

2018-06-11 13:08 GMT+02:00 Alan Hazelden <notifications@github.com>:
