### ISSUE TITLE
color in hex code colors 

### ISSUE THREAD

**Issue by increpare** [increpare/PuzzleScript#457]
color background and set foreground text color to white/black depending on background color

suggestion by https://twitter.com/ChrisZorg/status/1007357319418646528

**Comment by increpare** [comment]
tried it out but i wasn't able to get the parser to respect the word boundaries properly
<img width="457" alt="bildschirmfoto 2018-06-15 um 02 41 22" src="https://user-images.githubusercontent.com/465632/41444800-9e273b6e-7045-11e8-865b-490d69c9ed15.png">

my hack attempt at an implementation is here https://github.com/increpare/PuzzleScript/tree/regex-color-test

it seems there's some more tricking of the parser to do, but my codemirror-fu isn't up to the task!

**Comment by quietshu** [comment]
Found an interesting bug: 
```
Target 
#FF0 #ff0
```

Both black:
![image](https://user-images.githubusercontent.com/3676859/41451478-a5333e58-709f-11e8-8d6e-2a05231e79c8.png)

But `#FF0 #f00` looks okay:
![image](https://user-images.githubusercontent.com/3676859/41451509-c9f75dfa-709f-11e8-86ec-c359e79c2378.png)

**Comment by increpare** [comment]
It's live now.  Thanks, @quietshu :)
