### ISSUE TITLE
broken on IE

### ISSUE THREAD

**Issue by increpare** [increpare/PuzzleScript#461]
re https://github.com/increpare/PuzzleScript/issues/333#issuecomment-397568082

oops! guess you can't use ```Object.Assign```.  better replace it with something else that works...

**Comment by increpare** [comment]
@quietshu should be fixed now - did a check on https://netrenderer.de/index.php , but if you can easily confirm that it's working, that'd be nice! :)

**Comment by quietshu** [comment]
Yay it works. Confirmed in IE11/Edge Win10.
