### ISSUE TITLE
Feature request: custom sprite size

### ISSUE THREAD

**Issue by quietshu** [increpare/PuzzleScript#471]
Using sprites with more or less than 5 will output the warning "Sprites must be 5 wide and 5 high". It would be great if there's a `sprite_size` in preludes.

**Comment by increpare** [comment]
nope, I don't want to go out of my way to enable people to get caught up on looks over other aspects of the game - bigger sprites are also less usable to edit with a text editor.

**Comment by quietshu** [comment]
Thanks. The reason I need this feature is that I have to add "borders" to all those assets for a recent game idea. So 5x5 is not enough (without the borders it's only 3x3).

I understand your point. I don't think there're many people need this either. So after all I'm using a modified version of PS.

:)
