### ISSUE TITLE
link to third party tools in documentation

### ISSUE THREAD

**Issue by increpare** [increpare/PuzzleScript#479]
with solver, and the two sprite editors

**Comment by philschatz** [comment]
Yay for linking to 3rd-party tools!

I have been working on https://github.com/philschatz/puzzlescript-cli and am close to having something complete but I can submit a Pull Request if I do not finish in time.

The goals of that repository are to:

1. allow blind people to play PuzzleScript games (see [this section for details](https://github.com/philschatz/puzzlescript-cli#video-games-that-blind-people-can-play) )
1. run PuzzleScript games just in a terminal (so people can add them as easter-eggs into command-line tools or via a SSH connection)
1. allow people to embed PuzzleScript games into other places. For example:
    - 404 pages on websites (e.g. https://slack.com/404 or http://www.thecodepost.org/internet/play-hidden-t-rex-game-offline-chrome/ )
    - for kids to play (PuzzleScript games are great for teaching kids to think critically about how to solve problems in teams or on their own)

**Comment by increpare** [comment]
aha, that's very cute!

(Could you also use the legend renderer to make a version of games that
renders using the legend symbols (there's already a text generator that the
map editor uses), for the full ascii experience?  that would probably break
for a lot more games though because of symbols being missing)

2018-07-10 20:57 GMT+02:00 Philip Schatz <notifications@github.com>:

**Comment by increpare** [comment]
@pedropsi  already has a list of links to tools, so I don't need to do this, so closing https://pedropsi.github.io/game-tools.html
