### ISSUE TITLE
Monospace font not displaying in Chrome

### ISSUE THREAD

**Issue by variousauthors** [increpare/PuzzleScript#482]
I opened up the editor after a while and noticed that in Chrome the font is not monospace. I poked around in the CSS and it looks like the font is being overridden? Everything is fine in firefox.

This could very well be a problem with my own Chrome instance, looking for confirmation.

**Comment by increpare** [comment]
Apologies for not replying.  I amn't able to reproduce this myself fwiw, so am closing the issue.  Thanks for mentioning it.  Feel free to comment if you have any other questions about this, or if you can reliably reproduce it.
