### ISSUE TITLE
turning on and off editor seems to mess up verbose logging so it doesn't aggregate logs

### ISSUE THREAD

**Issue by increpare** [increpare/PuzzleScript#485]
https://www.puzzlescript.net/editor.html?hack=84333e7b1d0fb08979ff59a4e140ffb2

**Comment by ThatScar** [comment]
Darn, I thought I had reported this issue when I found it like a year ago, I have some more relevant information:
Anytime the editor is toggled, logs are no longer aggregated.
Logs are aggregated again upon Rebuild, which works regardless of whether the editor is open right now without changing its state :)
Any unaggregated logs (mostly ones from verbose logging, though) lag a significant amount if there are more than 50 or so per turn :(

**Comment by increpare** [comment]
oooh, good lead...some day I'll fix this...
