### ISSUE TITLE
Can't start message with section keywords

### ISSUE THREAD

**Issue by ThatScar** [increpare/PuzzleScript#490]
If you do `message objects swap instead of pushing`, it throws some errors and the word `objects` is highlit; any other section name like `levels` or `sounds` also doesn't work. Breaks both in rules and between levels.
https://www.puzzlescript.net/editor.html?hack=ce024f4e1808a3e5dfcf8c0ed9106ced

**Comment by increpare** [comment]
oops - good catch :)

Am Fr., 28. Sep. 2018 um 16:51 Uhr schrieb ThatScar <
notifications@github.com>:
