### ISSUE TITLE
Exported games hosted on itch no longer show the mobile tab menu

### ISSUE THREAD

**Issue by chz16** [increpare/PuzzleScript#494]
itch seems to have made some kind of change to the way it presents games on mobile that makes it so the tab menu with undo & restart in it no longer shows up, which is a big bummer. No idea if this one is entirely on itch's end, or if it's something you can/would do something about.

**Comment by increpare** [comment]
If I were you I'd check myself first, if I could, see if there are any errors in the js console, check which browsers it occurs on, and get back to me about it.  If you can't, link me to an example and I'll have a look :)

**Comment by chz16** [comment]
I hooked into the Mac iOS development simulator and there were no console messages of any kind. I've verified the menu doesn't show up on mobile Safari, and there's a report on the thinky puzzle Discord that it also doesn't show up on Chrome 70.0.3538.110 on Android 8.1.0.

Seems to affect all PS games on itch, I've verified these: 
https://chz.itch.io/punt-mazes 
https://chz.itch.io/maera-public-works https://jackkutilek.itch.io/movement-garden

**Comment by increpare** [comment]
Tried to reproduce this in debug "mobile emulation" mode in the browser (Chrome), and also on my iPad (Safari), and the undo/restart tab was ok in both modes. (Both the punt-mazes example and a game I uploaded just to double-check the current version).  Closing, but if it's still a problem for you let me know and I'll reopen.

**Comment by chz16** [comment]
Yep, looks good. I checked Movement Garden, which according to itch hasn't been updated since I filed this, and it also has a tab again, so I guess this one was on itch's end after all?
