### ISSUE TITLE
Allow newlines in messages

### ISSUE THREAD

**Issue by tobiasvl** [increpare/PuzzleScript#509]
Would be nice to display slightly more information in a pretty way, without making the player press X a bunch of times

Specifically, in many games all levels have a level number message before them, it'd be nice to be able to display some other message at the same time without having two messages.

Could perhaps be supported without breaking anything by allowing the string "\n" in a message.

**Comment by increpare** [comment]
Hi, thanks for the report :)


"Specifically, in many games all levels have a level number message before them, it'd be nice to be able to display some other message at the same time without having two messages."
I understand that some people might feel the pull of this, but.  Long messages aren't really something I want to go out of my way to facilitate.   If it's important to you, you can space it out with padding manually (though I understand that's a hassle).
