### ISSUE TITLE
Browser tab close keyboard shortcut is ignored and creates stuck key

### ISSUE THREAD

**Issue by roryokane** [increpare/PuzzleScript#51]
The W key gets stuck when I hit Command-W to close the tab in Firefox on Mac OS X. Not only does the tab not close, but also W (up) is continuously sent to the game until I press and release W again. Try it out when [playing a game](http://www.puzzlescript.net/play.html?p=6851495) – the character in that game will continuously jump when you hit Command-W.

This bug does not happen in Chrome for Mac. I have not tried other browsers or other keyboard shortcuts.

Related to #38.

**Comment by increpare** [comment]
probably fixed, given that related issues are fixed

**Comment by roryokane** [comment]
Testing this again, the issue with ⌘W described in the title was fixed—⌘W always works—but the related issues with ⌘A, ⌘S, and ⌘D I described in [this comment](https://github.com/increpare/PuzzleScript/issues/51#issuecomment-35485223) are still a problem.

In both Firefox 85 and Chrome 88 on macOS 10.14, I see that sometimes those three keyboard shortcuts ⌘A, ⌘S, and ⌘D fail to trigger their browser function and instead cause the game to repeat that motion as if the key were held down.

**Comment by increpare** [comment]
Thanks for getting back so quickly.  OK if you reload puzzlescript.net now it should be good (you may have to hit the reload button - in the puzzlescript console it will say V1.7)

**Comment by roryokane** [comment]
Yep, it seems to be fixed now in both Firefox and Chrome.
