### ISSUE TITLE
Nosave command?

### ISSUE THREAD

**Issue by dario-zubovic** [increpare/PuzzleScript#517]
I'm working on a game where pressing action key changes selection. Storing those in undo stack isn't exactly UX-friendly, so I've implemented nosave command in my fork of PuzzleScript. When triggered, engine doesn't store current turn to undo stack.

You can check it out here: https://dario-zubovic.github.io/PuzzleScript/play.html?p=ff17a0853ffb7de2e2209070d3228731

There are plenty of games which could use this. Is this something you want / should I make PR request (perhaps with a better name for the command)?

PS. Example with microban where new state is pushed to undo stack only when crates are moved: https://dario-zubovic.github.io/PuzzleScript/play.html?p=26c867a2c48d186479b23b1a7554c348

**Comment by increpare** [comment]
Dario, hi!  Cute game :) It never really bugged me when playing, for example, heroes of sokoban, so I don't really see the need.  It makes things a little better, but I don't find it compelling to introduce a whole new command for it.

Best :)
S
