### ISSUE TITLE
Better Emoji Support

### ISSUE THREAD

**Issue by jcmiller11** [increpare/PuzzleScript#518]
I did a little testing and emoji sort of work in some very limited cases.  I can define an object equivalent using emoji in the LEGEND and then use that name which contains them only in the SOUNDS section.

Ideally I'd like to be able to use them in CollisionLayers, Rules, WinConditions, and especially in the level maps.

**Comment by increpare** [comment]
There's no fixed emoji standard, unfortunately, which makes it hard to support.  I could support it better, but I've looked into it in the past and it's still a bit of a mess/inconsistent between browsers.  But yeah, I could support it better...should maybe look into it again :)

Thanks for the suggestion :)

**Comment by increpare** [comment]
Several years later, detecting emoji is still awful. (Detecting if something is a single grapheme - 'character' in unicode is hairy). Will investigate again in another few years.  Eventually it should be possible, right?

**Comment by increpare** [comment]
I looked into it (again).  Emoji support is still very different across browsers - many won't combine the family emoji for instance into a single symbol, and without that guarantee they can't be used in the legend, for instance, and if you can't get them working there then ... I don't know, it's complicated!

On the plus side the \p{Emoji} selector seems to work now, which is nice.  Adding these and using reg_name_no_spaces to match  win conditions seems to work better (cf https://gist.github.com/increpare/76e8d0f739d84ac8e6d4a72adbec8a16 )

    var reg_name = /[\p{Emoji}\uFE0F?\p{L}\p{N}_]+[\p{Z}\s]*/u;///\w*[a-uw-zA-UW-Z0-9_]/;
    var reg_name_no_spaces = /[\p{Emoji}\uFE0F?\p{L}\p{N}_]+/u;///\w*[a-uw-zA-UW-Z0-9_]/;

, but overall I'd rather keep the current quarter-assed emoji support than bring it up to half-assed support with the expectancy I can do anything about the remaining bugs.  If emoji support was consistent I wouldn't mind adding it, but it's not so yeah.

**Comment by increpare** [comment]
(might revisit in another few years :) )
