### ISSUE TITLE
Undo past level change in editor

### ISSUE THREAD

**Issue by minotalen** [increpare/PuzzleScript#522]
While in the editor, it would be nice to be able to undo past a level change.
This could be useful for the following things:
- restoring accidentally solved levels
- comparing two levels (CTRL+Click other level, then undo)

There are quite a few puzzlescript games which have level select. Those games would benefit from having this feature as a prelude keyword (maybe `levelundo`) so that accidental level changes can be remedied.

**Comment by increpare** [comment]
thinking about this - it makes some sense...

>There are quite a few puzzlescript games which have level select.
what do you mean?

Am Fr., 2. Aug. 2019 um 18:44 Uhr schrieb minotalen <
notifications@github.com>:

**Comment by minotalen** [comment]
Draknek made the level dropdown, Pedropsi has a level select in the game bar.
That means it's possible players accidentally switch levels, so it might be nice if one could enable this feature with a prelude keyword.

**Comment by increpare** [comment]
Ah right.  No that's not a convincing use-case for me.  Not adding more complexity to the engine/language for mods that other people are making.  But I will consider implementing it in the editor in future, trying it out, and adding it if it feels good.

**Comment by increpare** [comment]
So given that i misunderstood the original comment and took it to be about being able to undo level *edits* in the map editor (which is already possible), and given that level victory is not something one tends to want to undo (except sometimes to read messages one has skipped -_- ). I'm going to close this task.

I appreciate the suggestion though!
