### ISSUE TITLE
inspector tool

### ISSUE THREAD

**Issue by minotalen** [increpare/PuzzleScript#526]
Icon: I, placed to the right of S in the editor
when selected, clicking on a tile prints all objects on it to the console. Should be quite useful for debugging to know the state of a cell.

**Comment by increpare** [comment]
Late to comment on this - it sounds like a sort of thing that might be nice, but I'm very conservative about user flow/etc, adding complexity. I'm leaving this open because it might be a good idea and whenever I look into debugging features again I might try it out.

**Comment by increpare** [comment]
doing some spring cleaning - regarding this as an offshoot of  https://github.com/increpare/PuzzleScript/issues/78

**Comment by increpare** [comment]
[cells now show contents in map editor on hover]
