### ISSUE TITLE
Right click as sprite droplet tool

### ISSUE THREAD

**Issue by minotalen** [increpare/PuzzleScript#527]
Right clicking on the editor currently does nothing, I was thinking it might make sense if that would change the selected sprite to whats under the mouse, similar to the function of the color picker in FlickGame.

**Comment by increpare** [comment]
right clicking in the editor does do something already, it deletes the tile (Replaces it with background tile) - see  https://www.puzzlescript.net/Documentation/leveleditor.html for details :)

**Comment by minotalen** [comment]
Oof, I've even used that feature! Well I'd still prefer copying tiles but then again, being able to quickly place background is better. Do you think it would be a useful feature?
Maybe it would make sense for CTRL+click on a tile?
