### ISSUE TITLE
Removing background tiles breaks "no X" wincondition

### ISSUE THREAD

**Issue by zacharyabel** [increpare/PuzzleScript#534]
The "no X" wincondition seems to assume the presence of Background tiles everywhere (or at least on X), but it's also easy to remove or replace Background and thus invalidate the wincondition. Demonstration: https://www.puzzlescript.net/play.html?p=fcfd61e0895b008f83a4f89b827f4a22

**Comment by zacharyabel** [comment]
Note: this came up when replacing the default Background with a programmatic checkerboard pattern. Now I'm adding the checkerboard on top instead.

**Comment by increpare** [comment]
Thanks for this report.  Looks a bit fishy indeed.

As a workaround, you know you can have multiple background tiles right? (bg1, bg2, b3 in the objects section and then "background = bg1 or bg2 or bg3" in the legend)

**Comment by zacharyabel** [comment]
Ooh, I didn't know that. Thank you!
