### ISSUE TITLE
keyboard shortcut for commenting lines

### ISSUE THREAD

**Issue by RzvnB** [increpare/PuzzleScript#543]
Would be nice to have a shortcut for commenting a single line in the web editor.

**Comment by increpare** [comment]
Good suggestion. I agree maybe? But then maybe people would want it to work with general selections, which is slightly trickier...(ideally I'd want it to be a toggle comment/uncomment, which would want to be smart about a number of things)

**Comment by increpare** [comment]
Done!  Will probably upload tomorrow; just for the record the command is ctrl+/ .

**Comment by increpare** [comment]
@RzvnB Ok this is my favourite and most commonly used keyboard shortcut in puzzlescript now (maybe behind copy/paste).  Thank you so much for the suggestion!
