### ISSUE TITLE
Lose Condition

### ISSUE THREAD

**Issue by shadowtime2000** [increpare/PuzzleScript#544]
Is it possible that a lose condition could be added? Like a timer or just a condition like the win condition?

**Comment by increpare** [comment]
Hi, thanks for the suggestion!

Why would you want a lose condition?  Could you give some examples? What
would you want a lose condition to be, and how would it differ from
triggering the restart command [cf.
https://www.puzzlescript.net/documentation/rules.html] ?

Timers are not something I want to add in without some *very* strong
use-cases.  I feel people would use them to make games-with-time-limits
that I would not have any interest in playing. I try to avoid giving people
tools that (IMO) are very easy to misuse, and this sounds like it might be
one of them.

Am Mo., 13. Juli 2020 um 01:58 Uhr schrieb shadowtime2000 <
notifications@github.com>:

**Comment by shadowtime2000** [comment]
Using the restart command would send them back to their last checkpoint. What I am saying is a command or something so you can just end the game.

**Comment by increpare** [comment]
Just doing a review of feature requests. Apologies for the delay.  You didn't answer my questions, and I don't find the suggestion in the abstract very compelling given the considerations I already wrote, so I'm closing this for now.

Thanks for the suggestion nonetheless,

S

**Comment by increpare** [comment]
you can have a temporary token that's removed if there's a player and use it to trigger restart

late random [ ] -> [ temporarytoken ] (place one temporary token somewhere)
late [player] [temporarytoken] -> [ player ] []
late [ temporarytoken] -> restart

**Comment by soggychips** [comment]
Ah, that's great! Thank you!
