### ISSUE TITLE
please disable autocomplete in the levels section

### ISSUE THREAD

**Issue by minotalen** [increpare/PuzzleScript#546]
![image](https://user-images.githubusercontent.com/29110130/87362573-4c473c00-c56f-11ea-8c3a-5b97b8864818.png)

**Comment by increpare** [comment]
good idea, lol....

**Comment by increpare** [comment]
I tried reproducing this and couldn't - could you link me to a file that has this and say what you did to do it, along with what browser?

(Apologies for the late response)

**Comment by minotalen** [comment]
Try pressing lowercase m at the start of a line. (Tried in 'Kettle') Should autocomplete to message.

**Comment by increpare** [comment]
Thank you for the quick reply!

If you force reload that won't happen any more (suggesting'message' when it shouldn't).  However, I don't see how it could end up recommending 'section' like it did in the original shot tho -the only word that it seems like it should every be able to suggest there is 'message'.  Hmm.  Let me know if you can find any other words that cause problems :)
