### ISSUE TITLE
Music does not work

### ISSUE THREAD

**Issue by Brin-o** [increpare/PuzzleScript#547]
Hi!

In the current version that is posted on https://www.puzzlescript.net it is impossible to load music via the youtube command. 

Is there hope to this getting fixed or is it more a thing on youtube's end?

Thanks for making the engine, it's super fun!

**Comment by increpare** [comment]
Hi, thanks for leaving the comment. Unfortunately, at the best of times music embedding was a hack - youtube doesn’t want to be used that way and it needed constant maintenance over time. ( related #501 ).  Backwards-compatibility is important to me for puzzlescript, but this kind of external dependency on a service that doesn’t want to be served as we were serving it.  It might be if I look into it again I can get it working (or someone else can!).  But it’s possible that it’s just not possible to get working any more.
