### ISSUE TITLE
again and win fighting with eachother

### ISSUE THREAD

**Issue by increpare** [increpare/PuzzleScript#553]
https://www.puzzlescript.net/editor.html?hack=35b78c89f59ea8ea2e508ab03c299c91

win should win but again somehow has priority...still not sure what's going on  (hat tip to 00gogo00)

**Comment by sftrabbit** [comment]
I looked into this recently (in fact, that's my example!) and it seems to be related to the way that it'll try to determine if it even needs to schedule the next `again` turn by running a non-destructive turn that will exit early as soon as a rule changes anything. I guess it ends up being less non-destructive than expected. I'm not totally sure how the `win` causes the problem though - I didn't get that far.

**Comment by increpare** [comment]
Yeah, the 'feel ahead to see what will happen' nature of again makes debugging confusing ^^

**Comment by increpare** [comment]
@sftrabbit thanks for the bug-finding :)
