### ISSUE TITLE
Arrow keys to move is currently not working in Firefox 85.0.1 Win10 (WASD still works)

### ISSUE THREAD

**Issue by TerryCavanagh** [increpare/PuzzleScript#558]
Observed in https://www.puzzlescript.net/play.html?p=4adc7b17c2c0449c3a8b6c730e8cbfc9

**Comment by increpare** [comment]
Cool thanks :)

[note to self: it works on my iPad on safari]

**Comment by increpare** [comment]
[can reproduce on ipad firefox tho!]
