### ISSUE TITLE
win condition ignored if run in run_rules_on_level_start

### ISSUE THREAD

**Issue by increpare** [increpare/PuzzleScript#578]
https://www.puzzlescript.net/play.html?p=d5e23f75865be5a5ff54387491bf60f9

I think this is actually ok, but I should adjust the debugging message in this case.

**Comment by increpare** [comment]
brought to my attention in #574

**Comment by chz16** [comment]
The use case would be cutscene levels that play entirely without player interaction, which I have in a few of my games. I've always done it with animations and having the win come in an again turn though, I don't know if it ever worked on the initial execution turn. If it was always like this and wasn't recently broken like the other thing, then I guess it's not a pressing issue haha

**Comment by increpare** [comment]
Ah yeah, fair thoughts!  Thanks for sharing.  That's a possible use case; the sort of thing that maybe vexd edit or the like used.  It's as likely games rely on the existing behaviour as would want it otherwise though, and I'm not particular sure I want to go out of my way to cater to either use-case ^_^

**Comment by chz16** [comment]
Yeah, if that's how it always worked then you can go ahead and disregard this. I just ran into it while testing the other thing and assumed that it was also a recent regression.
