### ISSUE TITLE
Rules with objects that "can never overlap" creates exception

### ISSUE THREAD

**Issue by ThatScar** [increpare/PuzzleScript#605]
https://www.puzzlescript.net/editor.html?hack=ef66a98c7b55c697e6614f40e304930d
There's a commented section (that I expect to be identical to the uncommented section) that, when uncommented and run, throws this exception in the browser console:
`compiler.js:2161 Uncaught TypeError: Cannot read property 'lineNumber' of undefined`
This halts running/rebuilding/sharing.

First of all - it would've been easier if this was reported in the editor console (you can catch, then log error, then re-throw)
Otherwise, I am actually quite happy to see that the (non-bugged) + rules don't error anymore as they used to in earlier versions (which was just annoying). Now it's just "loop" that needs fixing and testing.

**Comment by increpare** [comment]
Thank you for the report + test case :)
