### ISSUE TITLE
check out some things from clementsparrow's branch and see if they're relevant to this one :)

### ISSUE THREAD

**Issue by increpare** [increpare/PuzzleScript#608]
https://github.com/ClementSparrow/PuzzleScript/commit/5cd1cbb35bf9e05c767d7f40e351812dd915d145
https://github.com/ClementSparrow/PuzzleScript/commit/7f94c755d2fea2bcdfb5f493225e9c7510fe2295
https://github.com/ClementSparrow/PuzzleScript/commit/80d1f0d845805e6fcd9b79947d75c9a62c6038d0

**Comment by ClementSparrow** [comment]
Oh, I just saw that. I think the second was fixing a bug that I introduced, but the first and third might be relevant for you.

**Comment by increpare** [comment]
@ClementSparrow while understanding that your fork is your thing and that's great, for what it's worth I wasn't able to understand what https://github.com/ClementSparrow/Pattern-Script/commit/5cd1cbb35bf9e05c767d7f40e351812dd915d145 orhttps://github.com/ClementSparrow/Pattern-Script/commit/7f94c755d2fea2bcdfb5f493225e9c7510fe2295 were fixing (without, say, an example game that exhibits the bugs).  Obv there's no requirement that your changes be self-explanatory, I thought I'd explain why I'm not pulling things back ^^

**Comment by ClementSparrow** [comment]
Yeah, I need to take the habit of submitting a bug report with a minimal working example before fixing the bug... Sorry if you spent some time on it.
