### ISSUE TITLE
Can't use "sfx" with "cancel"

### ISSUE THREAD

**Issue by musurca** [increpare/PuzzleScript#61]
Attempting to pair the "cancel" keyword with a "sfx" keyword gives the following error: "The CANCEL command can only appear by itself on the right hand side of the arrow."

Since "cancel" is often used to block illegal moves, it seems like it would be useful to allow some kind of feedback sound to alert the player. Why not allow "sfx" (and maybe even "message") to be the exception to this rule?

Thanks!

**Comment by increpare** [comment]
added a 'cancel' sfx now if you really want it
