### ISSUE TITLE
Add keyboard shortcut for Run button

### ISSUE THREAD

**Issue by m-ender** [increpare/PuzzleScript#610]
Unless I'm overlooking something, there doesn't seem to be a keyboard shortcut for the RUN button, just for REBUILD. Would you mind adding one for RUN as well, since some changes require a restart?

**Comment by increpare** [comment]
Try this combo: ctrl+enter, and then esc :P

(This is me saying I don't know if it's worth having a dedicated keyboard combo?)

I appreciate the suggestion though.
