### ISSUE TITLE
Directional properties

### ISSUE THREAD

**Issue by m-ender** [increpare/PuzzleScript#612]
This would be a slightly more involved feature, but I think it could be incredibly powerful. It would be really neat if we could define directional properties, i.e. properties made up of four objects which are assigned up/down/left/right roles. We'd then need some syntax to specify an absolute or relative direction when using the property, so the compiler can do the same kind of expansion it does for movement syntax.

A simple example of what we could do with this: the Gopher game includes a sliding feature where it remembers a movement direction on an object and then repeatedly moves that object automatically using `again`. Currently, this requires a bunch of rules in sets of four:

```
[ Gopher slider_R ] -> [ right Gopher right slider_R ]
[ Gopher slider_L ] -> [ left  Gopher left  slider_L ]
[ Gopher slider_U ] -> [ up    Gopher up    slider_U ]
[ Gopher slider_D ] -> [ down  Gopher down  slider_D ]

right [ right Gopher | SlidePellets ] -> [ right Gopher | slider_R ]
left  [ left  Gopher | SlidePellets ] -> [ left  Gopher | slider_L ]
down  [ down  Gopher | SlidePellets ] -> [ down  Gopher | slider_D ]
up    [ up    Gopher | SlidePellets ] -> [ up    Gopher | slider_U 
```

(There are some other rules around these sliders, but these are the ones we can simplify.)

Now let's imagine we could define `Slider` as a directional property, maybe something like this:

```
Slider = right slider_R or left slider_L or up slider_U or down slider_D
```

And then we could simplify the actual sliding rules to something like this:

```
[ Gopher Slider{>} ] -> [ > Gopher > Slider{>} ]
[ > Gopher | SlidePellets ] -> [ > Gopher | Slider{>} ]
```

This is just a simple example, but I could see this being really powerful in a lot of cases. (I'm currently trying to implement some larger rigid bodies that can change shape, and I find myself hardcoding tons of special cases that would collapse significantly if I could specify them using relative directions.)

I would imagine the `{...}` can take any of `<^>v`, absolute directions, and `vertical`/`horizontal`, and work analogously to movement.

**Comment by increpare** [comment]
Hello, and thanks for the suggestion.

Yeah, the advantages of some kind of templating/generics/macro system had crossed my mind. But in practice I've always been ok copy/pasting the variations myself.  If it's getting out of hand for you, then I'm sorry to hear that! Ok I think maybe once I implemented my own macro script to generate the rules for some game. 

Overall, the added complexity and difficulty of understanding/use, and risk of enabling over-engineering, for me seem to outweigh the benefits.

**Comment by m-ender** [comment]
That's fair enough! I wonder if I can hack something by temporarily replacing actual movement with a marker and then abusing movement as a kind of parameter (I couldn't easily communicate this state between turns but I might not need to).

**Comment by increpare** [comment]
ah yeah, directional markers like that can also be handy
