### ISSUE TITLE
Airport Agression is broken

### ISSUE THREAD

**Issue by Draknek** [increpare/PuzzleScript#613]
https://www.puzzlescript.net/play.html?p=bc929f97dfb013a5f62ab58ac2d117c0

**Comment by increpare** [comment]
Oh this is a tricky one; there's a typo in the code that's causing it (a
space is missing between one of the object names and its legend key in the
objects section).  Oh I can just ask jack to fix it...brb...

Am Mi., 14. Apr. 2021 um 13:47 Uhr schrieb Alan Hazelden <
***@***.***>:

**Comment by increpare** [comment]
fix'd
