### ISSUE TITLE
Easy Enigma - new font is a shame here

### ISSUE THREAD

**Issue by Draknek** [increpare/PuzzleScript#614]
https://www.puzzlescript.net/play.html?p=a95269130d520a58adf710b692d1e52e

Since this game recreates the title screen inside the game, it's no longer seamless since they don't match anymore

I'm imagining this is probably a wontfix, but wanted to bring it to your attention if it hadn't been already

**Comment by increpare** [comment]
Yeah, alas... (/thanks for mentioning!)
