### ISSUE TITLE
token objects

### ISSUE THREAD

**Issue by minotalen** [increpare/PuzzleScript#621]
Many PS games use token objects for advanced mechanics. Having to create an object definition, assigning them to a layer and adding the `[token] -> [ ]` rule are common tasks. Why not streamline that process?
A special naming convention (like _name) could mark an object as a token. They are transparent by default and get removed at the start of each turn. Each token type has their own layer.

```
[ activetile | player ] -> [ _temp | player ]
[ no _temp | player ] -> [activetile | player ]
```
... where temp is not mentioned anywhere else in the script
imo could make the script more concise and expressive.

**Comment by increpare** [comment]
Hey, thanks for the suggestion. It makes a lot of sense to suggest it.  I've also often used transient objects as tokens.
>Why not streamline that process?Because it's an extra feature to support, legacy concerns (would need to check it doesn't break older games), an extra class of object, and also most importantly an extra thing to learn and it might (though I'm not sure) make it harder to understand code generally (uniformity of presentation vs conciseness, I'm not sure which would win out).  For now I'd prefer to keep things simpler, though I totally get where you're coming from, and I appreciate the suggestion!
