### ISSUE TITLE
not sure why, but autofill box is too small sometimes

### ISSUE THREAD

**Issue by minotalen** [increpare/PuzzleScript#622]
![grafik](https://user-images.githubusercontent.com/29110130/115967959-aa10a780-a535-11eb-8a60-0ee0ef0c075e.png)
this was FF, but I remember it happening in other browsers

**Comment by increpare** [comment]
Thanks for the report!  What OS?

**Comment by minotalen** [comment]
Windows10
here's a source in case that helps: https://pastebin.com/LVTGexDA

**Comment by minotalen** [comment]
ok so I can't currently reproduce the bug in either vanilla or the fork I'm in.
Please close this, if I ever figure out how it happens and how to consistently repro I will let you know. Sorry for the inconvenience!

**Comment by increpare** [comment]
It may perhaps have been due to zoom level? ( ctrl + )

Am Sa., 24. Apr. 2021 um 21:22 Uhr schrieb mino ***@***.***>:
