### ISSUE TITLE
smart paste

### ISSUE THREAD

**Issue by minotalen** [increpare/PuzzleScript#623]
pasting code that contains at least one SECTION could get pasted in a smart way (each section part gets added to the end of their respective section while duplicate SECTION declarations get ommited).
That way players could exchange modular snippets and easily combine them. I imagine it to be useful for collaboration as well.

I imagine the workflow being an added dialogue when pasting a snippet, that asks users if they want to smart paste or just insert it regularly.

**Comment by increpare** [comment]
Hi, thanks for the suggestion.  I get kind of where you're coming from, but it sounds very finnicky to specify/difficult to implement/tricky for users to understand.  I prefer paste being paste.  So closing :)

**Comment by minotalen** [comment]
alright no probs! lmk if I should filter my suggestions more ;)

**Comment by increpare** [comment]
Suggestions are welcome, but please do note that I'm super conservative
about adding new features (both to keep the software easy to use as well as
to keep my workload from growing out of control) :)

Am Sa., 24. Apr. 2021 um 22:03 Uhr schrieb mino ***@***.***>:
