### ISSUE TITLE
realtime turns triggering [stationary Player] rules

### ISSUE THREAD

**Issue by minotalen** [increpare/PuzzleScript#624]
Is it intended that realtime turns trigger rules with `stationary player` in them? I'm trying to prevent a certain action when a direction key is held.  Sadly this does not seem to be possible because realtime is enabled.  
idk, are there games that require this trigger, is it intended? If so, disregard this request.
One way to make both work might be to trigger `stationary player` during realtime as well when no direction is pressed.

**Comment by increpare** [comment]
This feels more like a usage question - I'd ask on the mailing list - https://groups.google.com/g/puzzlescript .  If you ask there, ideally with more details, more people can offer suggestions (and honestly I'm a big foggy on what exactly the possibilities are without playing around with realtime, which I'm not in the mood for right this moment)

**Comment by minotalen** [comment]
Heh alright. I have 'fixed' this edge case rather inelegantly with the usage of invisible markers, bringing the one turn with missed input. I'd argue that the player is not really stationary if they move before and after a realtime turn, but maybe that is just my misconception.
