### ISSUE TITLE
restart bug

### ISSUE THREAD

**Issue by increpare** [increpare/PuzzleScript#627]
https://www.puzzlescript.net/play.html?p=8cb44a28cdc2c7c18d54243ff31b5606

https://www.puzzlescript.net/editor.html?hack=8cb44a28cdc2c7c18d54243ff31b5606

why does action trigger level complation?

**Comment by sftrabbit** [comment]
Additionally, your response to issue 382 suggests you didn't intend to allow `message`s to show before a `restart`/`cancel`, unless you changed your mind recently. Worth noting that even when the messages were bypassed, it is easy enough to make a message show before `restart`/`cancel` just with a couple of extra rules.

**Comment by sftrabbit** [comment]
Another thing that might influence the decision: if you go with the new behaviour of `restart`/`cancel` not bypassing messages, there's a separate bug that would need to be fixed.

Let's say a `message A` and `restart` happen at the same time, but we also have `run_rules_on_level_start` and one of the rules that runs on start has `message B`. When the `restart` happens, the level is restored and the rules are run immediately, and the `message A` never happens.

To untangle this, the restoring of the level would have to somehow wait until after the message screen has been dismissed. That seems like it could be a bit of a pain and have cascading effects elsewhere.

**Comment by increpare** [comment]
Thanks for your detailed description/thinking through of the issue, and communcating the weird edge-case from the discord, submitted as a separate bug report here - #676
