### ISSUE TITLE
Closing brackets in messages close comments

### ISSUE THREAD

**Issue by minotalen** [increpare/PuzzleScript#630]
```
(((
message example)))
[ player ] -> [  ]
)))
```
The closing brackets in the message end the comment, which I suppose is not intended. Worth noting that a message like `message test (comment)` and  `message test (comment` will work fine, just stumbled upon this quirk by using a smiley in a message :)

**Comment by increpare** [comment]
I think I'm ok with this behaviour as is, even though it might seem a bit silly.  At some point in the future I might change my mind and decide it's a bug, but not for now.  Thanks for the report though :) (so: #wontfix)

**Comment by minotalen** [comment]
ha that's alright, was assuming so :D well at least it's documented now haha

On 12 May 2021 21:20:49 Stephen Lavelle ***@***.***> wrote:
>
> Closed #630.
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.


Sent with Aqua Mail for Android
https://www.mobisystems.com/aqua-mail
