### ISSUE TITLE
Simulation should pause when window is not visible

### ISSUE THREAD

**Issue by salty-horse** [increpare/PuzzleScript#638]
Games with `realtime_interval` are running constantly, even when I tab away.
I think puzzlescript should detect when the window is not visible (with the [`visibilitychange` event](https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilitychange_event)?)

Unscientific measurement: Playing _Skipping Stones To Lonely Homes_, Firefox reports the hidden tab's "Energy Impact" as High.

**Comment by increpare** [comment]
I think I agree with you.  Thank you for this suggestion :)

**Comment by increpare** [comment]
Thinking that browsers should do this already, this is possibly relevant: "Firefox does not throttle inactive tabs if the tab contains an AudioContext." [ https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout ]
