### ISSUE TITLE
Separate gallery and engine in two distinct repositories

### ISSUE THREAD

**Issue by ClementSparrow** [increpare/PuzzleScript#644]
Maintaining forks of PuzzleScript is hard and takes time, but the gallery is usually not relevant for the forks. Since every game added to the gallery causes a new commit, it makes it harder to keep forks up to date with vanilla PS.

**Comment by increpare** [comment]
Splitting into forks makes more work for me.  One repo for the whole website works best for me, though I understand that's not necessarily great for others.

**Comment by increpare** [comment]
(/ thanks for the suggestion!)
