### ISSUE TITLE
"The requested URL was not found on this server." errors?

### ISSUE THREAD

**Issue by increpare** [increpare/PuzzleScript#670]
Is anyone else getting these for www.puzzlescript.net? Sometimes I just get a white page with this message (happened a lot in Switzerland, not happening so much anymore), but when I reload everything's ok again...

**Comment by increpare** [comment]
@saljam randomly, do you know how to go about checking if something that might be related to my host (nearlyfreespeech.net) doing weird cdn stuff/not always caching it correctly.  I don't know if there are any easy ways to investigate this kind of behaviour...

**Comment by increpare** [comment]
(oh, wait maybe it's just my own personal server that's messing up and not puzzlescript's. nvm ... )

**Comment by increpare** [comment]
(I just got the problem on www.increpare.com, which is the same host, so it's *probably* a host-wide thing)

**Comment by saljam** [comment]
is it a static page?

it doesn't look like it's using a cdn for the home page. i'm getting the same ip address from dns and same last few hops on traceroutes from a bunch of different locations.

if your host load balances across multiple servers (and they most likely do) one explanation might be that one of their servers was unhealthy or broken but wasn't take out of rotation for a while.

another might be that something on your local network was trying to mess with your request. i've had mobile providers try to redirect me to ads on some 

if it still happens to you, maybe try to see how what proportion of requests are broken and ask your host about it?

this is a command to try 100 times and groups counts by status code (i'm assuming the error gets status 404).

```
for i in $(seq 100); do curl -s -I https://www.puzzlescript.net | head -1; done | sort | uniq -c
```

i couldn't reproduce your issue though. i tried it and all i get is status 200 OK.

**Comment by increpare** [comment]
I'm very appreciative that you, as someone who knows somewhat more about this domain than me, were able to have a look and didn't see anything obviously amiss.  I didn't get any broken requests either when I ran that one-liner (either for puzzlescript.net or increpare.com), so I'm going to just assume this is some weird temporary hiccup and open the issue again if it continues to be a problem.

Thanks!
