### ISSUE TITLE
right [ > Player | ] -> [ Player | Player ]🐱‍🐉

### ISSUE THREAD

**Issue by increpare** [increpare/PuzzleScript#679]
Should 

```right [ > Player | ] -> [ Player | Player ]```

clear movements in both tiles?

Should 

```right [ Player | ] -> [ Player | Player ]```

propagate movements? 

Does `right [ player | ] -> [ | player ]` even propagate movements? 

( from https://github.com/increpare/PuzzleScript/issues/492#issuecomment-890224072 )

**Comment by increpare** [comment]
1 - yes
2 - ok I randomly did something where it now does this so whatever it's fine
3 - nope it doesn't, so let's just leave it like that - it'll probably break a bunch of stuff to have this implicitly expand as
``right [ moving player | ] -> [ | moving player ]````
``+right [stationary player | ] -> [ | stationary player ]````
or whatever.

**Comment by ThatScar** [comment]
Unfortunately, some old games accidentally relied on similar bugs/quirks/inconsistencies.

**Comment by increpare** [comment]
I try to be pretty careful about not breaking old games - the changes didn't trip any errors in my test database.  It's possible some things got broken, but, welp, I hope not.  I'll add some more tests tonight for older games.  If you can think of any possibilities (or can test them locally before I push it live), let me know!

**Comment by increpare** [comment]
I went through all games in the gallery that didn't have tests and added one for each - they all seem to work ok, even the ones that have lots of errors ^^

**Comment by ThatScar** [comment]
I probably mixed it up with some other quirk that you have already accounted for, no worries.

**Comment by increpare** [comment]
so many quirks! 😅

**Comment by increpare** [comment]
[I did find in the end one game in the wild that I broke with this change - https://github.com/increpare/PuzzleScript/issues/697 , but that was one of mine from a few weeks ago ]
