### ISSUE TITLE
gist not loading - ERROR HTTP Error 401

### ISSUE THREAD

**Issue by Draknek** [increpare/PuzzleScript#689]
I'm seeing this error on all puzzlescript games hosted on puzzlescript.net.

In the browser's network inspector, I see a GET request to e.g. https://api.github.com/gists/dbb32000738925f19cd89453e64b54c0 with a return status of 401. If I navigate to that URL myself, it works fine - only seems to be when the request is from puzzlescript that there's a problem.

I first noticed this a day or two ago, but it's still happening.

It seems to work on other forks
https://www.puzzlescript.net/play.html?p=dbb32000738925f19cd89453e64b54c0 - doesn't work
https://auroriax.github.io/PuzzleScript/play.html?p=dbb32000738925f19cd89453e64b54c0 - works
https://dario-zubovic.github.io/PuzzleScript/play.html?p=dbb32000738925f19cd89453e64b54c0 - works

**Comment by increpare** [comment]
weird. I guess you tried force refreshing? I can't repro here. Hmmm! I did
make a change recently that might be the cause


Alan Hazelden ***@***.***> schrieb am So., 1. Aug. 2021,
13:58:

**Comment by Draknek** [comment]
yup, have force refreshed. It is weird indeed! not sure why it's only affecting me

**Comment by Draknek** [comment]
More information: in an incognito tab it works as expected

**Comment by increpare** [comment]
also, what browser/os are you using, and what country are you in?

Stephen Lavelle ***@***.***> schrieb am So., 1. Aug. 2021, 14:08:

**Comment by Draknek** [comment]
Chrome, UK

**Comment by increpare** [comment]
Seems like using invalid oauth tokens, as added in https://github.com/increpare/PuzzleScript/pull/606 , make requests fail.  As there's no way to check in advance if a token is valid, I'm just going to revert that, and hopefully it'll work. I'll let you know when I've pushed the changes live and ask you to check again.  Thanks for the report, Draknek!

**Comment by increpare** [comment]
@Draknek I was able to repro the issue on chrome, and it's not happening now (on https://www.puzzlescript.net/play.html?p=dbb32000738925f19cd89453e64b54c0 for instance. you may need to force reload). Fingers crossed there's no problem now for you either :) 🤞

**Comment by Draknek** [comment]
Confirming this works for me now! Cheers.
