### ISSUE TITLE
syntax highlighter - word sfx0 requires a space after it before it's recognised

### ISSUE THREAD

**Issue by increpare** [increpare/PuzzleScript#700]
![image](https://user-images.githubusercontent.com/465632/127992265-747cd446-4aa5-4828-a33e-43c1f267b551.png)

**Comment by ClementSparrow** [comment]
You still have an issue with other sound section words that also need a \b at the end:
<img width="163" alt="image" src="https://user-images.githubusercontent.com/52840159/129741981-fae98de6-8e87-4f43-9ed2-4a494bba9003.png">

It also produces a strange error message:
<img width="464" alt="image" src="https://user-images.githubusercontent.com/52840159/129742231-f26decf7-c7d2-4f59-8025-2860fd392758.png">
