### ISSUE TITLE
cf "Fix a bug allowing a tag completion to double an entry if it matches a valid object name."

### ISSUE THREAD

**Issue by increpare** [increpare/PuzzleScript#712]
https://github.com/ClementSparrow/Pattern-Script/commit/bce5a8640ba19949db881aa3188275dd492d72a4

**Comment by ClementSparrow** [comment]
The bug concerned the tag system that I introduced in the fork (the syntax Object:tag), so I doubt the problem exists also in vanilla PuzzleScript.

PS: I'm not used to work on forks, so please tell me if I can do anything to help you.

**Comment by ClementSparrow** [comment]
> I'd say, one thing you could do, if you do fix bugs locally that're likely to be in the main branch, or other small tweaks, just cc me @increpare so I don't miss it (ideally describing what the bug is ^^ ).

OK, I will do that. For the tweaks, I will try to submit directly a pull request if it's not too much work for me to make one, otherwise I will @ you in a comment for the commit, with an explanation.

**Comment by increpare** [comment]
Cool, thanks :)

Am Mi., 11. Aug. 2021 um 12:29 Uhr schrieb ClementSparrow <
***@***.***>:
