### ISSUE TITLE
horizontal rules over-expanded?

### ISSUE THREAD

**Issue by increpare** [increpare/PuzzleScript#721]
https://www.puzzlescript.net/editor.html?hack=44c3cc19a7691abfb209bbd485c17f55

```
[ horizontal player ] -> [ target ]
```

becomes

```
(83) DOWN [ left player ] -> [ stationary target ]
(83) DOWN [ right player ] -> [ stationary target ]
(83) RIGHT [ left player ] -> [ stationary target ]
(83) RIGHT [ right player ] -> [ stationary target ]
```

**Comment by ClementSparrow** [comment]
In my fork I've added a comment a long time ago in the function directionalRule, saying "TODO: should'nt it also include 'perpendicular' and 'parallel' but exclude 'horizontal' and 'vertical'?" I guess it's the source of this problem.

https://github.com/ClementSparrow/Pattern-Script/blob/master/src/js/compiler/rule_parser.js

**Comment by ClementSparrow** [comment]
The "it" in that comment being the variable defined as:

    var relativeDirections = ['^', 'v', '<', '>','horizontal','vertical'];

**Comment by increpare** [comment]
Lol.  You saved me a few hours probably.  Thanks.
