### ISSUE TITLE
optimisation: concept of 'deleting'/'chain-reaction'/'potential-decreasing'/'one-loop' rules that don't need to be in rule-groups?

### ISSUE THREAD

**Issue by increpare** [increpare/PuzzleScript#726]
```
[  > Player | Crate  ] -> [  Player | Crate  ]
```
or
```
[ player | crate ] -> [ | crate ]
```

this only removes things - this means it will never *create* opportunities for new rules so in some sense doesn't need to be in a rule-group
UNLESS it happens to specify 'no X' (damnit)

If a rule-group has only deleting rules, you don't need to traverse a second time after.  This might be worthwhile and speed up simulations a bunch.
OTOH https://github.com/increpare/PuzzleScript/issues/722 could similarly attack this situation (for the case of the first rule. for the second I already have measures taken).

(don't like the 'deleting' terminology because it obscures the crucial 'no' requirement. maybe 'chain-reaction' (or something with 'potential-decreasing') )

**Comment by increpare** [comment]
Might be worth seeing what % of rule-groups in the test-suite count as 'potential-decreasing'?

**Comment by ClementSparrow** [comment]
Also, in that specific example, you're moving the Player and Crate one cell to the right (assuming the rule direction is right), so it's not only deletions.

**Comment by increpare** [comment]
Oh that's true.  I should've picked a better rule ^^

**Comment by increpare** [comment]
Don't know if it's worth detecting when this could be done. Gonna skip it.
