### ISSUE TITLE
clementsparrow: [re: x no x warning] The current implementation seems to throw warnings when it's not strictly necessary. An example from Vertebrae:

### ISSUE THREAD

**Issue by increpare** [increpare/PuzzleScript#754]
The current implementation seems to throw warnings when it's not strictly necessary. An example from Vertebrae:

    late up [ rayU | rayBlocker no DartWallD ] -> [ | rayBlocker ]

because `DartWallD` is a member of the property `rayBlocker`, and this property is not on a single layer, so it's expanded for all its members, which gives the expanded rule:

    late up [ rayU | DartWallD no DartWallD ] -> [ | DartWallD ]

This is another case of #21, also related to #20.

_Originally posted by @ClementSparrow in https://github.com/ClementSparrow/Pattern-Script/issues/19#issuecomment-899498118_

**Comment by ClementSparrow** [comment]
I added the warning message, you just discard the rule silently. So you will not have the problem of the warning triggering when it seems inappropriate. But you may have the problem of discarding a whole rule without telling it to the dev.

**Comment by increpare** [comment]
Ah right.  I was going to say that I throw an error when rules are totally discarded because of all the 'X no X's getting discarded, but nope it turns out I wasn't ( https://github.com/increpare/PuzzleScript/issues/762 ) . Thanks for causing me to look into it :)
