### ISSUE TITLE
Checkpoint causes the same level to be played again and again

### ISSUE THREAD

**Issue by ClementSparrow** [increpare/PuzzleScript#773]
to reproduce:
- Paste [this file](https://github.com/increpare/PuzzleScript/files/7025587/checkpoint_broken.txt) in the editor and run the game ('new game').
- Press down, then right. Because the player was on a target and a rule triggers a CHECKPOINT in that case, a checkpoint command is issued.
- Now, reload the page (even clearing the cache if you want), paste the file again, run the game and select 'continue'. You will continue playing from the same point as before reloading the page, as expected.
- Solve the level without stepping on another target (e.g., up, down x 3, left, up) and expect to play the second level.
- No, it reloads the first level from the same checkpoint.

The reason seems to be that `curlevelTarget` is set when the page loads and a checkpoint is found in local storage, and again when the title screen is displayed, but it will be set to `null` only when a new game is started, the end of the game is reached, a specific level is loaded from the editor, or a checkpoint has been reached in the level that we just won. So if we load a game from a checkpoint and then complete the level without triggering another checkpoint, the next level will be loaded and then replaced with the content of `curlevelTarget` that has not been set to `null`.

Additional remark: the bug will not appear if the level state saved after a checkpoint triggers another checkpoint after it's loaded. So if you just place a checkpoint with a rule like `late [ player checkpointPosition ] -> checkpoint`, the bug will not appear.

**Comment by increpare** [comment]
Thanks for the detailed report.  Helped me track it down pretty quickly :)

**Comment by ClementSparrow** [comment]
Mhhh... The bug still happens, for me. It seems you forgot to recompile the scripts?

**Comment by increpare** [comment]
I, thanks for checking.  I indeed hadn't recompiled/reuploaded stuff to
puzzlescript.net, but have now following your comment.  I did verify it
locally, and just now ( cf
https://www.puzzlescript.net/play.html?p=fdcecb898c389f89e5ca6a0e2685d011 -
you may have to force-reload to get the fixed version).  I haven't verified
that it's good with the fully standalone version, but I'd guess it should
be.

Funny that the bug didn't come up before now.

If you notice any problems, let me know - thanks again for the heads up :)

S

Am So., 22. Aug. 2021 um 20:32 Uhr schrieb ClementSparrow <
***@***.***>:
