### ISSUE TITLE
Consider supporting "sub-properties" to allow leveraging properties in more cases

### ISSUE THREAD

**Issue by Brinsky** [increpare/PuzzleScript#788]
# Background

PuzzleScript supports defining "properties" shared by multiple objects to allow writing rules that apply the same logic to all of them:
```
Moveable = Crate or Boulder
```
```
[ > Player | Moveable ] -> [ > Player | > Moveable ]
```

# Proposal

One case that this doesn't cover currently is when objects that share a symmetric behavior but still need object-specific patterns:
```
late [ Crate Target ] -> [ GlowingCrate Target ]
late [ Boulder Target ] -> [ GlowingBoulder Target ]
```
If you have >3 objects that conceptually share a property but still need this kind of behavior, it gets pretty verbose.

You could imagine defining overrideable "sub-properties" on each property to streamline this case:

## Example syntax 1:
```
Moveable : GlowingMoveable = Crate : GlowingCrate or Boulder : GlowingBoulder
```
```
late [ Moveable Target ] -> [ GlowingMoveable Target ]
```

## Example syntax 2:
```
Moveable (GlowingMoveable, DisabledMoveable) = Crate (GlowingCrate, DisabledCrate) or Boulder (GlowingBoulder, DisabledBoulder)
```

---

I'm not sure if "sub-properties" is actually the best term for these. In a traditional OOP context I might call `Moveable` an interface or a class and then call the overrideable values  (e.g. `GlowingMoveable`) properties or members.

Final note: here's [one example game](https://www.puzzlescript.net/play.html?p=9044a8b4cf78d6ebd16020bbc1dadb25) where I've struggled with repetitious rules that would be made cleaner by a feature like this.

**Comment by increpare** [comment]
Hey, thanks for the suggestion.  I've come to be weirdly ok with swathes of almost-but-not-quote copy-pasted code as preferable to adding new syntax for something like this - I've always just wished for tagged wildcards or the like.  I'm still on the 'no' side, but maybe some day it'll change.  Anyway, I definitely see where you're coming from!

> Final note: here's one example game where I've struggled with repetitious rules that would be made cleaner by a feature like this.

That's not so bad - you should see some of the things I've written ... 🙃

**Comment by Brinsky** [comment]
Thanks for taking a look!

> I've always just wished for tagged wildcards or the like 

I'd be curious to see an example - something like this? (syntax particulars aside)

```
late [ $1 Target ] -> [ $2 Target ] {
    Crate, GlowingCrate;
    Boulder, GlowingBoulder;
}

```

**Comment by increpare** [comment]
For me more like

[ $1 target ] -> [ Glowing$1 target ]

matching/compiling to

[ Crate Target ] -> [ GlowingCrate Target ]
+ [ Boulder Target ] -> [ GlowingBoulder Target ]

Something lazy like that ^^

Am Mo., 22. Nov. 2021 um 16:18 Uhr schrieb Brian Stottler <
***@***.***>:
