### ISSUE TITLE
can't run games on latest firefox and some other browsers

### ISSUE THREAD

**Issue by lee2sman** [increpare/PuzzleScript#791]
For latest firefox i'm finding i can load but can't start games. they all have the same start screen, which says Puzzle Script Terminal v1.7 Insert Cartridge. 

I'm getting this in current Firefox as well as (obscure browsers) Falkon, Qutebrowser. Chrome seems fine. I don't have a mac so can't test on there. Any idea of tests to try in order to provide more info? I haven't tried puzzlescript in a few months perhaps but i didn't have any issues previously.

I'm on a Linux running Ubuntu 18.04.

**Comment by increpare** [comment]
Hi, thanks for the report.

I just tried to load a game and couldn't reproduce on osx.

If you could give me some more information so we can narrow it down?

Could you confirm that this particular game doesn't work?
https://www.puzzlescript.net/play.html?p=58325085befa37ab497168cd803c64cb

When the error is happening, could you open up the javascript console (
Ctrl + Shift + J I think ) and let me know if there are any errors there?

Best,

S

Am Di., 30. Nov. 2021 um 04:52 Uhr schrieb Lee T ***@***.***>:

**Comment by lee2sman** [comment]
Hmmmm, it's intermittent for me! Firefox is working for me now after a restart, so since I can't reproduce exactly, maybe we should close.

I still have the issue in Falkon browser and qutebrowser, but seeing as these are used by an extremely small audience likely, maybe not worth investigating? (There is no inspector  / javascript console in these as far as i know)

**Comment by lee2sman** [comment]
I'm going to close this, as i can't reproduce anymore on Firefox, so either my firefox is updated or I had some kind of javascript blocker going on that I couldn't find.
