### ISSUE TITLE
backup & restore instead of rigid

### ISSUE THREAD

**Issue by rmmh** [increpare/PuzzleScript#80]
Explicit backup & restore commands could be more intuitive than rigid, while allowing similar (greater?) power.

Here's an example, which is a simple extension of Scott Hughes "Iterated Extended Rigid Body Test", and uses random to apply a rule at most once: 

```
======
LEGEND
======
Box = Box1 or Box2 or Box3 or Box4
Blocker = Player or Box or Wall

=====
RULES
=====
startloop

(pick one player to handle)
random [ > Player | Box ] -> [ > Player | > Box ] backup

( propagate movements )
  [ > Box | Box ] -> [ > Box | > Box ]
+ [ moving Box1 | Box1 ] -> [ moving Box1 | Box1 ]
+ [ moving Box2 | Box2 ] -> [ moving Box2 | Box2 ]
+ [ moving Box3 | Box3 ] -> [ moving Box3 | Box3 ]
+ [ moving Box4 | Box4 ] -> [ moving Box4 | Box4 ]

( try moving everything )
[ > Blocker | no Blocker ] -> [ | Blocker ]

( back out if anything was blocked )
[ > Blocker | Blocker ] -> restore

( cancel player's movement if it was blocked (we just restored) )
[> Player | > Box ] -> [ Player | Box ]

endloop
```

Backup makes a copy of the game state _when it runs_ (after the rule it's attached to applies), restore sets the game state back to that copy. Restore without a preceding backup goes back to the beginning of the turn.

This seems more straightforward than the spookiness of rigid reverting and re-executing with a rule disabled, and fits nicely with mental models of cancel/checkpoint/restart.

Name possibilities: {backup,save,try,remember}/{restore,load,undo,revert}

**Comment by increpare** [comment]
I think it's fair to say that this won't be happening ^^  Legacy support/etc. .  Closing.
