### ISSUE TITLE
remove object/layer limit

### ISSUE THREAD

**Issue by increpare** [increpare/PuzzleScript#81]
Right now puzzlescript has a hard limit of 32 objects and 6 layers, owing to its internal architecture (for instance, for collision purposes, each object is represented by one bit of a 32-bit int).  At some point this limit should be removed, when computers and/or javascript get super-fast.  It'd be real nice, wouldn't it?  However, it'd involve a total engine rewrite.  So, maybe in a couple of years.

(mainly just made this so that I can direct people who ask to it)

**Comment by rmmh** [comment]
Thank you for the lovely Christmas note! I don't really know how to respond to the warm fuzzy feelings, but it brightened my holidays.
