### ISSUE TITLE
buttons to mute music/sfx

### ISSUE THREAD

**Issue by rmmh** [increpare/PuzzleScript#82]
Music and sound effects can be annoying. People should be able to easily toggle them.

**Comment by increpare** [comment]
my suggestion. press m to mute, toggles between muting audio/sfx/blah - youtube embedding is pretty flakey right now, expect it to not fully work.

**Comment by increpare** [comment]
fixed by https://github.com/increpare/PuzzleScript/commit/a8cd415feef0dadcf2fd350f7ab819ba3758cdf2

**Comment by increpare** [comment]
(took a while!)
