### ISSUE TITLE
Comments near rules not treated like whitespace

### ISSUE THREAD

**Issue by MisshapenSmiley** [increpare/PuzzleScript#858]
I add a rule like:
```
(oioioi) [ Player ] -> [ Player ]
```
And I get the following error:

`The start of a rule must consist of some number of directions (possibly 0), before the first bracket, specifying in what directions to look (with no direction specified, it applies in all four directions). It seems you've just entered "OIOIOI)".`

It happens for any of these, albeit with varying errors:

```
(oioioi) [ Player ] -> [ Player ]
[ (oioioi) Player ] -> [ Player ]
[ Player (oioioi) ] -> [ Player ]
[ Player ] (oioioi) -> [ Player ]
[ Player ] -> (oioioi) [ Player ]
[ Player ] -> [ (oioioi) Player ]
[ Player ] -> [ Player (oioioi) ]
```
Not `[ Player ] -> [ Player ] (oioioi)`, though, that one works fine.

**Comment by increpare** [comment]
Thanks for the bug report.  The code for compiling rules isn't the same as the code for highlighting them - I should integrate the two and probably allow comments inside because why not...

Oh right I already have it as an issue from a while back, this duplicates #337
