### ISSUE TITLE
Delayed action

### ISSUE THREAD

**Issue by RobotCaleb** [increpare/PuzzleScript#911]
I was trying to make a prototype of something I've built several times over the years.
I'd like to do an input and x number of game frames later that same input would be applied to the specified actor. I was unable to see anything related to this in the documentation.

Totally understand if this isn't generally useful enough for inclusion.

Thanks!

**Comment by increpare** [comment]
I guess the way to do that would be to have a series of countdown objects that get replaced each turn.  Support for this at a language level would be overkill I think.

I appreciate the request however - thanks :)
