### ISSUE TITLE
Can move title screen cursor after making a selection

### ISSUE THREAD

**Issue by Auroriax** [increpare/PuzzleScript#918]
1. Go to the title screen of a game for which you already have save data (so you have both the new game & continue options)
2. Press the selection button (for example on continue)
3. Before the menu disappears, press the up or down button. Now the other option is selected, and that option will be executed instead of the initially selected one.

Expected: Once you make a menu selection it is "locked in" and you cannot make any more inputs until the menu disappears
Actual: You can move the cursor, and the menu will pick the position the cursor is on when the menu disappears.

I have fixed this in my fork, see commit https://github.com/Auroriax/PuzzleScriptPlus/commit/871aa4103d7d8cda7f3cf2ae16a7f6f8db106ff5

GIF:
![puzzlescript_bugreport_titlescreen](https://user-images.githubusercontent.com/6784890/167128654-cc7b2735-f6db-4a3c-8d22-003bfecb42fb.gif)

**Comment by increpare** [comment]
lol good catch :)
