### ISSUE TITLE
Make the code editor mobile-friendly

### ISSUE THREAD

**Issue by odog8** [increpare/PuzzleScript#921]
The puzzlescript editor doesnt show everything on mobile, eg. the run, export buttons.

**Comment by increpare** [comment]
What device are you using? Could you post a screenshot?  I feel like the editor can't really support Mobile phones because of how much stuff is going on, but I do aim to support tablets (and have used it on tablet myself).

**Comment by increpare** [comment]
On the other hand, the question of how to display the options when the window is too narrow is maybe a good one - maybe it'd be better to increase the size of the toolbar in that case and have the things over two lines? Hmm!

**Comment by odog8** [comment]
![Screenshot_20220609-161810_Chrome](https://user-images.githubusercontent.com/36713157/172946519-5a62c494-70d5-4a88-99c7-a704970d3f5a.jpg)
Everything works, except the toolbar at the top, and the drop-downs. If the toolbar scrolled it would be better. This is a stretch, but what if you put the editor and player in different 'tabs'?
