### ISSUE TITLE
You can make sprites size other than 5x5, and they are also the wrong size

### ISSUE THREAD

**Issue by odog8** [increpare/PuzzleScript#927]
Sprites can be weird sizes. Here are some examples:
```
Player
pink red
10101
01010
10101
01010
```
You'd think this would be 4x5, but it's 4x4. And so is _this_:
```
Player
pink red
1010
101
101010
1
```
You can also make 2x2 and 3x3 sprites as well. Heresy!

You can make 6x6 and up sprites as well, but you need to avoid making a full 5x5 sprite or the lines after will be parsed as names. And some other weird things happen, too, a 7x7 sprite only copies the first 6 pixels width-wise no matter what.
```
Player
pink red
101010
010101
101010
010101
1010
010101
```
Notice the 4-long one to prevent the parser from noticing.

But that's not the worst part: they're also not the right size!
Because of some Math.floors in src/js/graphics.js, you get small pixel width and height sizes.
![image](https://user-images.githubusercontent.com/36713157/173723350-1cf4964d-19ca-4810-88f3-2de4a97c7e1e.png)

Sorry this is a bit long, but I thought it would be nicer to explain stuff than just leave it there.

**Comment by increpare** [comment]
Hi, thanks for the pull request.  I appreciate the work that went into it.  However, non--5x5 sprites are not supported by the engine and produce a warning message.  I don't see any reason to adjust the behaviour to make them look not weird.  Also maybe some pre-existing games are using the weirdness for some reason or other.
