### ISSUE TITLE
Alternative programs

### ISSUE THREAD

**Issue by zzo38** [increpare/PuzzleScript#930]
I posted this list on the issues because I am not sure where else to put it. All of the below are FOSS programs.

- [PuzzleScript+](https://github.com/Auroriax/PuzzleScriptPlus/): A fork of PuzzleScript with many new features, including being able to change the picture sizes, level selection menu, mouse controls, etc.

- [Puzzle Engine](https://github.com/HParker/puzzleengine): An implementation of PuzzleScript in C (I think this goes with one of the FAQ entries). A few things do not work yet, but many things do work.

- [Free Hero Mesh](http://zzo38computer.org/fossil/heromesh.ui): A rather different programming language (it was made as a clone of MESH:Hero Hearts, but now has many additional features too), but meant for similar purposes than PuzzleScript ("turn-based, keyboard-controlled puzzle games where you're moving a thing, or several things around"). Has some advantages and disadvantages compared with PuzzleScript; you can also do arithmetic, attaching variables to objects, diagonal movement, inventory, and many others. However, it is only known to run on Linux (it is not tested on other systems), and binaries are not currently available (you must compile from source).

- ZZT/MegaZeux: They are for a different kind of games, although they are still based on the grid and keyboard control and objects moving, and you can have levels with puzzles in them too.

There are probably others too, but I have not checked. (A proper comparison might also be of interest.)

**Comment by increpare** [comment]
I don't know where the right place to discuss this is - there's probably somewhere, but it's not here - I try to keep the core project focussed on maintenance.  Maybe on the discussion forum - https://groups.google.com/g/puzzlescript .
