### ISSUE TITLE
Some chars in prelude tags are not escaped properly, and these can cause exported games to fail compilation

### ISSUE THREAD

**Issue by Auroriax** [increpare/PuzzleScript#932]
e.g. if you give a game the title of a HTML tag, for example `<script>`, then you will be allowed to share export the game, but for the export, the generated file is not valid HTML5 and it will cause the HTML5 code to run into errors and the game to fail to load. It seems that some characters (the `<` and `>` brackets in this example, possibly more) are not always escaped properly.

Note that this only affects exported games and not share links.

**Comment by david-pfx** [comment]
I suggest you supply an explicit repro case including a sample (tiny) game.

**Comment by increpare** [comment]
(there's already a repro in the linked issue)

**Comment by david-pfx** [comment]
I thought I might have a look at it, but since I can't build the standalone right now I guess there isn't much point.

**Comment by david-pfx** [comment]
I've had a look, I can fix it. But I don't see any easy way to test it.

My motto is: if you can't test it don't write it. Might have to make an exception for this one.

**Comment by david-pfx** [comment]
Replaced by single purpose PR
