### ISSUE TITLE
errors detected during compilation

### ISSUE THREAD

**Issue by increpare** [increpare/PuzzleScript#934]
https://www.puzzlescript.net/play.html?p=6872613

**Comment by david-pfx** [comment]
Line 343
`HORIZONTAL [ > AppleBloom | NO obstacle No Player][JumpVariableB1][ -> [ | AppleBloom ][JumpVariableB]`

Bad code, extra '['. What's the issue?

**Comment by increpare** [comment]
This is a game that previously compiled + ran without problem.  For puzzlescript it's important that old games that compiled don't break in future versions, even if they contain clear errors (aka legacy support).  What I plan to do is to downgrade it from an error to a warning.
