### ISSUE TITLE
I can't no longer share through GitHub in PuzzleScript

### ISSUE THREAD

**Issue by Stingby12** [increpare/PuzzleScript#944]
For #943, I wanted to showcase how it looks like in the engine, but when I try to click the link to get permission, it gave this :

"HTTP Error 0 -"

I have a GitHub account as seen in the comment and I already got permission on another devise, so I didn't know what caused to get me this.

**Comment by increpare** [comment]
Thanks for this report!  Ok I tried and got the same error.  I just went and fixed up my certificate settings and now it works.  Could you confirm it's working for you as well?

**Comment by Stingby12** [comment]
Alright it's working !
