### ISSUE TITLE
Rule message prevents rule win

### ISSUE THREAD

**Issue by leo-chartier** [increpare/PuzzleScript#962]
When two rules trigger on the same event, one with a message and one with a win statement, the win is triggered but the message prevents it from happening.

How to reproduce:
https://www.puzzlescript.net/editor.html?hack=c0509bffd2bc637e018c003e430ade45

**Comment by increpare** [comment]
thanks for the report 

duplicates #962 

(I think of it as being a reasonably low priority awkwardness so haven't lept to deal with it)
