### ISSUE TITLE
Inconsistent behaviour on compile with errors

### ISSUE THREAD

**Issue by david-pfx** [increpare/PuzzleScript#965]
`MAX_ERRORS` is set to 5 in `compiler.js`. If this limit is hit the compiler emits a console message and exits.

The HTML system error message 'Errors detected during compilation' is then not hit, so there is no error message during export. A bad export will fail silently.

`MAX_ERRORS_FOR_REAL` is set to 100  in `parser.js`, so the function `TooManyErrors()` and its message is never hit.

Suggested fix: remove `MAX_ERRORS` and any tests using it.

**Comment by increpare** [comment]
example file
https://www.puzzlescript.net/editor.html?hack=0c29e2bd592aab925c38dc6645d68579

note that building produces errors to the console, but if you export, the downloaded file doesn't show any errors
