### ISSUE TITLE
Make us able to add properties/objects to ellipses...

### ISSUE THREAD

**Issue by JoaoFelipe3** [increpare/PuzzleScript#969]
Please. This currently gives us an error. It would help in making some games where this feature is needed.

For example:
```
[... Circle] -> []
```
The code above would remove all lines of circles.

Bonus feature: Add an optional length property to ellipses, typed as a number right next to the ellipsis.

Example:
```
[...4 Circle] -> []
```

Would only remove lines of 4 circles.

**Comment by increpare** [comment]
cf. https://github.com/increpare/PuzzleScript/pull/218

I'm going to close this, because my feelings haven't changed.  But I appreciate the suggestion.
