### ISSUE TITLE
On startup query string may execute before all files loaded, and then crash

### ISSUE THREAD

**Issue by david-pfx** [increpare/PuzzleScript#970]
The startup code in `editor.js` looks like this:
```
var fileToOpen=getParameterByName("demo");
if (fileToOpen!==null&&fileToOpen.length>0) {
	tryLoadFile(fileToOpen);
	code.value = "loading...";
} else {

```
It is possible for the query string to execute and try to load the file before all the JS files are loaded, causing a crash. 
The solution is simple. https://stackoverflow.com/a/11258137/1105562

```
window.addEventListener('load', function() {
    // your code here
})
```

I've checked it out and it works.

**Comment by increpare** [comment]
good catch, thanks. Note to future, bug-fixing self: check you don't need to reduplicate this fix in the player

**Comment by david-pfx** [comment]
I was able to reproduce it easily running locally:
`http://localhost:8000/src/editor.html?demo=sokoban`

It's likely to turn up in other places, so it's going to need some thought where the fix should go. Over to you!

**Comment by increpare** [comment]
I looked into this, but I'm not sure how to reproduce it.  I've tried in private mode, both hosting locally and on puzzlescript.net, force refresh, different browsers.  I wonder if there are some tools that might let me slow down the serving of specific files.

@david-pfx 
Can you remember what browser/operating system (including versions) you were using the cause this behaviour?

**Comment by david-pfx** [comment]
I mostly use the .bat file to run locally and (latest) Chrome for testing.

**Comment by increpare** [comment]
Note to future self:
I can consistently reproduce it on Chrome on MacOS, only in the src build (the compiled version compiles everything to a single js file, so won't exhibit this error), by opening up the network tools and turning on bandwidth throttling, but not deactivating the cash, and reloading.

<img width="747" alt="Bildschirmfoto 2024-04-27 um 16 16 38" src="https://github.com/increpare/PuzzleScript/assets/465632/e55391c1-8538-4755-a229-278666708f94">
