### ISSUE TITLE
Sprites smaller than 5x5 get an error but seem to work OK

### ISSUE THREAD

**Issue by david-pfx** [increpare/PuzzleScript#973]
I just found that sprites smaller than 5x5 get the error message: `Sprite graphics must be 5 wide and 5 high exactly`, but seem to work perfectly. Why not just allow them?

Repro object:
```
s3
black red blue
012
201
120
```

**Comment by increpare** [comment]
I decided that 5x5 was an aesthetic sweet spot for making things easy/quick to edit while still having readability.
