### ISSUE TITLE
Test 467 leftrightnpcs passes with 2 errors, but really there are 3

### ISSUE THREAD

**Issue by david-pfx** [increpare/PuzzleScript#975]
The correct errors for this program are
```
 line 58 : You named an object "<", but this is a keyword. Don't do that!
line 59 : You named an object ">", but this is a keyword. Don't do that!
line 95 : Maps must be rectangular, yo (In a level, the length of each row must be the same).
```
But the test only looks for the first two of these, and the test passes when it should not.

**Comment by david-pfx** [comment]
Actually I think there is an underlying problem here. The test harness is trying to compare errors and ignore warnings, but the list of error message text does not distinguish. It's not hard to fix, but it has to __want__ to be fixed.

At the same time I would suggest checking for compilation aborted, throw etc. And some improvements in the way the results are presented. Which I've done in PS Next.

**Comment by increpare** [comment]
The purpose of the compiler error tests is to trigger particular errors.
If I add new error messages they may get triggered by the old tests, and if
I require that the error tests have the same error output, that would
create extra maintenance work of updating the old tests which I want to do
as little as possible.  What I normally do when I add a new error message
is to add a new test to reproduce it.  So basically I don't do this to keep
the workload down when new error messages are added, and I'm okay with
this. (Re-running tests also risks me messing up and messing up tests).

Am Mi., 7. Juni 2023 um 15:43 Uhr schrieb david-pfx <
***@***.***>:
