### ISSUE TITLE
Levels can not contain glyphs that resemble section names

### ISSUE THREAD

**Issue by jcmiller11** [increpare/PuzzleScript#976]
If I create objects with the following glyphs for defining levels: S, O, U, N, D and attempt to create a level where they appear in a particular order in a line such as 
`####...`
`#.O#...`
`#..###.`
`#@P..#.`
`SOUNDS.`
`######.`
I get a bunch of errors since the parser seems to think I'm trying to define a second SOUNDS section, expected behavior is that the objects assigned to those glyphs appear in the level.

**Comment by jcmiller11** [comment]
Related bug, you can use the glyph after object name convention in the objects section to define an object's level glyph as =, which works until you try to put it at the start of a line in the level definition.

**Comment by david-pfx** [comment]
Which is a bug. The parser should assume a level if possible. For PS, the test for all EqualsRow and sections can be suppressed in the LEVELS section. For some forks it may be harder.

**Comment by increpare** [comment]
https://www.puzzlescript.net/editor.html?hack=b1975b25783ea51b3509f6c822fc487d repro example

**Comment by david-pfx** [comment]
So what does this change do? It's quite a bit of code plus a test case, to do what?

**Comment by increpare** [comment]
@david-pfx select "hide whitespace" and it'll look a bit simpler

![Image](https://github.com/user-attachments/assets/d05c3c68-fc24-4f1c-be7b-29beaefba8f5)

Basically, once we get to the 'levels' section there's no need to try look for section names any more.

**Comment by david-pfx** [comment]
Thanks! My problem is P:S allows sections in any order and PS Next needs to navigate compatibility with both. I think I need to tweak the test case.
PS Next will already pass a test case based on the original issue with `SOUNDS.`, just not one with a line that looks exactly like a section header.
