### ISSUE TITLE
Related bug, you can use the glyph after object name convention in the objects section to define an object's level glyph as =, which works until you try to put it at the start of a line in the level definition.

### ISSUE THREAD

**Issue by increpare** [increpare/PuzzleScript#977]
Related bug, you can use the glyph after object name convention in the objects section to define an object's level glyph as =, which works until you try to put it at the start of a line in the level definition.

_Originally posted by @jcmiller11 in https://github.com/increpare/PuzzleScript/issues/976#issuecomment-1613059905_

**Comment by david-pfx** [comment]
Easy fix: disable tests for equals row and new section in LEVELS section.

**Comment by increpare** [comment]
https://www.puzzlescript.net/editor.html?hack=652d4489c0960f23c3022b3470dd6f59 repro example

**Comment by increpare** [comment]
>Easy fix: disable tests for equals row and new section in LEVELS section.

Except that after every LEVELS there's an equals row by default ^^

Uh, there's no good solution here - I'm going to loosen up the parsing a little - it might in principle break things for people who use ======= as a between-level spacer *and* have '=' set as a type of object. I hope such people are few....

<img width="1060" alt="Bildschirmfoto 2024-12-03 um 16 14 20" src="https://github.com/user-attachments/assets/a3055c81-6d79-4d35-aa8d-41158c11df29">

**Comment by increpare** [comment]
hmm...maybe I'll still require something other than a = to also be on the line...just to be safe...

**Comment by increpare** [comment]
<img width="989" alt="Bildschirmfoto 2024-12-03 um 16 21 55" src="https://github.com/user-attachments/assets/051ec102-3a0b-4c9b-a6ad-80e72f4106cf">
more than a bit pathological, but if you've managed to do this, hopefully it makes sense why....

**Comment by increpare** [comment]
<img width="1157" alt="Bildschirmfoto 2024-12-03 um 16 23 24" src="https://github.com/user-attachments/assets/5616b1fc-3662-4c89-8da6-cfa445b72c39">
if anyone does this, they get what they've deserved -_-
