### ISSUE TITLE
Program with message and again hangs on input

### ISSUE THREAD

**Issue by david-pfx** [increpare/PuzzleScript#981]
Program attached. Just press Left then Right and it hangs.

[freeze_bug.txt](https://github.com/increpare/PuzzleScript/files/13482892/freeze_bug.txt)

**Comment by david-pfx** [comment]
Actually, found it. Function `restoreLevel` fails to clear `messagetext`. So at around `engine.js:902` add:

`messagetext="";`

**Comment by increpare** [comment]
(thanks!)

**Comment by increpare** [comment]
messagetext is a rather unfortunate not-quite internal-state, not-quite-interface state variable - if you do restart and cancel, cancel shouldn't cancel the messagetext.  the proper solution is probably to have the state have its own 'messagetext' variable, and then a different one for the interface that gets told about it after the end of a turn.  But this would need even more thinking.  So for now, I'm just clearing it in the one place where it's very safe to : in the place where the require_player_movement is set.
