### ISSUE TITLE
Cannot host the standalone build because it contains .gz files

### ISSUE THREAD

**Issue by david-pfx** [increpare/PuzzleScript#982]
The `build-standalone.bat` script goes to a lot of trouble to build a whole bunch of .gz files. Why?

I was not able to host this on my web site until I deleted them all. It's an Apache server, Chrome browser, pretty standard, and it just serves up the .gz files for download instead of as a site.

You can see it here (sans gzip files): https://puzzlescriptnext.polyomino.com/

**Comment by ClementSparrow** [comment]
build-standalone.bat is deprecated (and it's role was not to install PS on a server). To install P:S just copy the files and it should work.

**Comment by david-pfx** [comment]
No. 

 

The BAT file is just the handy Windows way to run compile.js under Node. It does a whole bunch of useful things required for a proper release, including minification and substituting some variables, and leaves the final result in /bin. 

 

Yes, I know you’ve abandoned this step, but I regard it as important. I plan to keep doing a pre-release of the /src version through GitHub, and the final release version(s) of the /bin version on my web site. As Stephen already does, it seems to me.

 

And it all works perfectly, except for the final step, building the gzip files. And my question is just: why do that?

 

Regards

David M Bennett FACS

  _____  

Polyomino Games – Programming Languages and Players for Games and Puzzles -- http://www.polyomino.com <http://www.polyomino.com/>

**Comment by jcmiller11** [comment]
https://stackoverflow.com/questions/9076752/how-to-force-apache-to-use-manually-pre-compressed-gz-file-of-css-and-js-files

**Comment by david-pfx** [comment]
Thanks. I'm not surprised it's a thing and that there are solutions for it. My question was: why create a problem where really none exists. So I no longer build the gzip files and it all works just like it says on the tin.

**Comment by increpare** [comment]
Th gz compilation stuff is specific to getting puzzlescript to load as quickly as possible for users (rather than sending uncompressed files, or compressing them on the fly) on my server setup.  I think I would have benchmarked everything along the way, but that was as long time ago.   The standard non-compiled version should still be hostable without compilation (it'll just load more slowly).

https://www.walkingclub.org.uk/utils/apache-brotli-compression.html seems like an overview with some numbers

This is server-configuration/hosting particularity on your end, so I'm marking this as closed.

**Comment by david-pfx** [comment]
My hosting is generic bog standard, and I have no wish to add settings specifically to deal with this problem. The default (no gzip files) is guaranteed to work. Your solution is not, and for me it does not.

If you are going to make this choice, my view is that you should document it in the development readme, and set out the reasons so others can decide for themselves.

And no, the non-standalone build does not show the build number and date, so I have no wish to publish that.
