### ISSUE TITLE
Visual debugger mangled on previous levels

### ISSUE THREAD

**Issue by david-pfx** [increpare/PuzzleScript#985]
Whenever verbose logging spans levels of different sizes, the visual debugger display of earlier levels is mangled. In this case it's levels 1 and 8 of Microban, but the effect is persistent across all puzzles.

![visual-dbg-level-bug](https://github.com/increpare/PuzzleScript/assets/12763741/10258b02-49f1-433b-a58b-95a1a6284faf)

How to fix? My inclination is to suppress visual debugging on all but the current level.

**Comment by increpare** [comment]
Good catch.

> My inclination is to suppress visual debugging on all but the current
level.
Thinking of a reason this might be unfortunate: you might want to debug
what happens to trigger level-end conditions.

I'm away from my computer this week, but here's my improvised note to
future stephen/whoever might wish to tackle this bug:

The 'correct' behaviour functionality should be to display the previous
level in a non-glitchy way.  I'm away from a computer this week, but I
remember some specific level-size/resolution related code to decide if to
change the canvas scale settings, so one should probably re-check that at
the start of every attempt to draw the debug view (and every return to
normal view from debug view).  It might not be that big a change.  (being
sure to double-check that everything works in flickscreen mode).

Am Mo., 5. Feb. 2024 um 13:49 Uhr schrieb david-pfx <
***@***.***>:

**Comment by david-pfx** [comment]
OK, let's see if that's possible. Currently `debugPreview()` has a call to `redraw()`, which is never going to work. It might be enough to just set the current level and call `resizeCanvas()` instead (and reverse it out in `debugUnPreview()`. But I agree, `flickscreen` and friends might be a problem.

This turned up while I'm working on adding level branching to PS Next, which means lots of level hopping. So keeping the debug working is likely to be a good idea.

**Comment by david-pfx** [comment]
Yes, that fixes it. Here are the changes I made (in PS Next):
```
function debugPreview(turnIndex,lineNumber){
	diffToVisualize=debug_visualisation_array[turnIndex][lineNumber];
	canvasResize(diffToVisualize.level);
	//redraw();
}

function debugUnpreview(){
	diffToVisualize=null;
	canvasResize();
	//redraw();
}

	var debugTimelineSnapshot = {
		width:level.width,
		height:level.height,
		layerCount:level.layerCount,
		turnIndex:debugger_turnIndex,
		lineNumber:lineNumber,
		objects:new Int32Array(level.objects),
		movements:new Int32Array(level.movements),
		commandQueue:level.commandQueue.concat([]),
		commandQueueSourceRules:level.commandQueueSourceRules.concat([]),
		rigidMovementAppliedMask:level.rigidMovementAppliedMask.map(a=>a.clone()),
		level: level,
	};

function canvasResize(level) {
    level ||= curLevel;
    canvas.width = canvas.parentNode.clientWidth;
    canvas.height = canvas.parentNode.clientHeight;

    screenwidth = level.width;        // board size, used to calculate cell size
    screenheight = level.height;

```

**Comment by david-pfx** [comment]
Re commit: graphics.js line 940 appears unintended.

You might save quite a bit of grief by not having 'level' as a global. It's ambiguous in several places.

**Comment by increpare** [comment]
@david-pfx you mean graphics.js line 540? https://github.com/increpare/PuzzleScript/commit/bc0beae86660e26f0ec15598b50b3ef8168ea7c0#diff-8f0d1b4aa4b66b688e4a75e16b361ccde1b2e074838aa6a0e6183a9995cfe459R540 yeah - not the end of the world though :)
