### ISSUE TITLE
editor: s should have 'save to console' tooltip in status area

### ISSUE THREAD

**Issue by increpare** [increpare/PuzzleScript#991]
<img width="236" alt="Bildschirmfoto 2024-04-22 um 11 56 34" src="https://github.com/increpare/PuzzleScript/assets/465632/17e3605f-7095-4e66-b613-02873d1cdbd5">

**Comment by david-pfx** [comment]
There are other missing tooltips. Is this the start of something bigger?

**Comment by david-pfx** [comment]
On the toolbar it's the Save and the two Load dropdowns. But once you start putting tooltips inside the game window or the console, there are lots of candidates.
