### ISSUE TITLE
syntax highlighter chokes on line starting with ") ====" but compiler understands it...

### ISSUE THREAD

**Issue by increpare** [increpare/PuzzleScript#997]
<img width="1377" alt="Bildschirmfoto 2024-04-27 um 01 26 17" src="https://github.com/increpare/PuzzleScript/assets/465632/c0a02c98-0148-44b5-b996-b6d46c7c0374">

not sure what the desired behaviour is - doing nothing seems good enough more or less, but some message might be good 😅

**Comment by david-pfx** [comment]
Are there tests in the test suite for all these fixes?

 

Regards

David M Bennett FACS

  _____  

Polyomino Games – Programming Languages and Players for Games and Puzzles -- http://www.polyomino.com <http://www.polyomino.com/> 

 

From: increpare ***@***.***> 
Sent: Saturday, 27 April 2024 9:27 AM
To: increpare/PuzzleScript ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [increpare/PuzzleScript] syntax highlighter chokes on line starting with ") ====" but compiler understands it... (Issue #997)

 

Bildschirmfoto.2024-04-27.um.01.26.17.png (view on web) <https://github.com/increpare/PuzzleScript/assets/465632/c0a02c98-0148-44b5-b996-b6d46c7c0374>  

not sure what the desired behaviour is - doing nothing seems good enough more or less, but some message might be good 😅

**Comment by increpare** [comment]
Assuming you're talking about the other small bug-fixes from yesterday?   Tests only cover core compiler/engine behaviour.  Anything beyond (interface bugs, networking) that gets hairy very fast.  Let's look at the last four code fixes.

#932 would be awkward to write a test for - download a page then load it, then check that the right tag is being displayed.  There is a mild risk of regression, in case I ever add back this compiler optimisation by accident.  

#996 doesn't deal exactly with DOM behaviour, but rather handwritten interface code.  Uh, it would be rather awkward to write code to produce this behaviour automatically, and also to detect that the correct behaviour is being observed (though maybe I could use a proxy like adding a debug message).  Low risk of regression.

#988 is browser-specific.  I could write a check that the link is generated with the correct 'download' attribute, but testing that the download works would be awkward because it's very browser-specific.  Low change of accidentally breaking it.

#995 could be tested in a browser with input simulation and then inspecting javascript variables afterwards.  That's probably the most amenable to browser-DOM testing.  A low risk of regression, I'd say.

The game engine is complex and it's very easy to break things accidentally when fixing other things (regressions would definitely happen regularly when fixing compiler bugs if I didn't have a test suite).  The things mentioned above, while they could break (and while I do occasionally break things), just don't carry the same risk.  Also, making tests for the engine/compiler is very easy, and writing tests for each the above would be much more involved (and they would be likely much more fragile).

**Comment by david-pfx** [comment]
All I can really say is it's a shame. The one thing a long-lived product like PS really deserves is a comprehensive test suite that nails its specified behaviour and can be used to check for bugs and regressions. SQLite is my go-to example.

**Comment by increpare** [comment]
duplicates #1033
